[package]
name = "time-series-store-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Python bindings for time-series-store"

[lib]
name = "time_series_store"
crate-type = ["cdylib"]

[dependencies]
chrono = { workspace = true }
ndarray = { workspace = true }
numpy = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module", "abi3-py310", "chrono"] }
time-series-store-core = { workspace = true }
