[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "d50f847ab6790bb52249b56590c169af5088885a"
libc = "glibc"
os = "linux"

    [[libinfrastore_ffi.download]]
    sha256 = "708dcc3baaee2d4e5ca9c63b0c877307fc0bb5ec35d5e1aff2ce75355bd7b56c"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.9.0/libinfrastore_ffi.x86_64-linux-gnu.tar.gz"
[[libinfrastore_ffi]]
arch = "aarch64"
git-tree-sha1 = "aedfedd3c2548cb20e03ec787aeef90ec5d2090f"
libc = "glibc"
os = "linux"

    [[libinfrastore_ffi.download]]
    sha256 = "d159075e4117ccae810f621a1558911cb1933862aef7c91b6ba5939222ac50f7"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.9.0/libinfrastore_ffi.aarch64-linux-gnu.tar.gz"
[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "b262ca3897af07dd5e7993318415fd6e34801996"
os = "macos"

    [[libinfrastore_ffi.download]]
    sha256 = "318c2c63736cf39953f5c72e6c2c54295974874c83074814455d4da31f782445"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.9.0/libinfrastore_ffi.x86_64-apple-darwin.tar.gz"
[[libinfrastore_ffi]]
arch = "aarch64"
git-tree-sha1 = "a67b690e120f53128a9e918a9b03021a2d1371c9"
os = "macos"

    [[libinfrastore_ffi.download]]
    sha256 = "b6d10bab06686336980372cf4eaa8931e81518e30324d77e15076b491126b962"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.9.0/libinfrastore_ffi.aarch64-apple-darwin.tar.gz"
[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "13dd10c25702fbb88b4f21e694e347ea45865f7a"
os = "windows"

    [[libinfrastore_ffi.download]]
    sha256 = "f492def4c242d256a9dab1864ed177dcd1cf1d58fcad0ea551153227e938d2c5"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.9.0/libinfrastore_ffi.x86_64-w64-mingw32.tar.gz"
