[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "4dc14567dc49396658d95f396edb708002cf4a34"
libc = "glibc"
os = "linux"

    [[libinfrastore_ffi.download]]
    sha256 = "1815a7e935af51397bab9b7f8e2cf5bb56bdf603cabd33af3a29e9f3380bfc4d"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.12.0/libinfrastore_ffi.x86_64-linux-gnu.tar.gz"
[[libinfrastore_ffi]]
arch = "aarch64"
git-tree-sha1 = "5dcedc355f2145852e976e51be89d84d57b72c89"
libc = "glibc"
os = "linux"

    [[libinfrastore_ffi.download]]
    sha256 = "2fe495be32fffe96e73ace4057554bedc7ffa39a8599154385785528ae03dc74"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.12.0/libinfrastore_ffi.aarch64-linux-gnu.tar.gz"
[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "56aa3a92d61da89d0dadb21cc0a253d18870d0ea"
os = "macos"

    [[libinfrastore_ffi.download]]
    sha256 = "ea7ad5787eabc84d68e9d5f70c053101952f31185c64f02289127d8b94d49902"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.12.0/libinfrastore_ffi.x86_64-apple-darwin.tar.gz"
[[libinfrastore_ffi]]
arch = "aarch64"
git-tree-sha1 = "87c426f9f5ebefeffc970a3f938622ef9888fba2"
os = "macos"

    [[libinfrastore_ffi.download]]
    sha256 = "e52b187b5bc7a10596892070af7622bc9339c5639bd3852f8655f728931d7144"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.12.0/libinfrastore_ffi.aarch64-apple-darwin.tar.gz"
[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "cb1b6abf48f0952bcd9176ac79dacfb0b0e956db"
os = "windows"

    [[libinfrastore_ffi.download]]
    sha256 = "87a395091e1cd5c772ab18dc4ed4291de5b6267c5288285ec2d690c08d7a89c2"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.12.0/libinfrastore_ffi.x86_64-w64-mingw32.tar.gz"
