[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "8be7f1bbe3279a5b78c989d70e012696c5e571d9"
libc = "glibc"
os = "linux"

    [[libinfrastore_ffi.download]]
    sha256 = "65f0f48396846d0c278c4f80f24659a7584869f1a863d9c87a2e1a3cc06b3c93"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.10.0/libinfrastore_ffi.x86_64-linux-gnu.tar.gz"
[[libinfrastore_ffi]]
arch = "aarch64"
git-tree-sha1 = "0840bac9718f41f24ea3874bf77f4d5f41e942ff"
libc = "glibc"
os = "linux"

    [[libinfrastore_ffi.download]]
    sha256 = "371fa67ddb4f1ab80347324f81a8fc53f4fed7f6aef19c86b36e9b8b7c8baa8d"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.10.0/libinfrastore_ffi.aarch64-linux-gnu.tar.gz"
[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "199eeb7f7f581884d8b4c97c271ffac965e97b74"
os = "macos"

    [[libinfrastore_ffi.download]]
    sha256 = "7566a7dccbc8ff160f44e543407295f3fc66c94e89a18178ee4ad343ff754401"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.10.0/libinfrastore_ffi.x86_64-apple-darwin.tar.gz"
[[libinfrastore_ffi]]
arch = "aarch64"
git-tree-sha1 = "14d782ffb9072aad247a0a9cd203c3d38302985c"
os = "macos"

    [[libinfrastore_ffi.download]]
    sha256 = "4d78193ed13599ad7d5c18674883e4fbf48c2c430ba294af9f13971b87b31c11"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.10.0/libinfrastore_ffi.aarch64-apple-darwin.tar.gz"
[[libinfrastore_ffi]]
arch = "x86_64"
git-tree-sha1 = "d8de4e13fd382f266e77fd344475757c7e9af508"
os = "windows"

    [[libinfrastore_ffi.download]]
    sha256 = "1c8c61f6b56df5376cb48fb76941d4b692feb38b68dd15a72ddc04c169cac7a4"
    url = "https://github.com/NatLabRockies/infrastore/releases/download/v0.10.0/libinfrastore_ffi.x86_64-w64-mingw32.tar.gz"
