/* Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef TIME_SERIES_STORE_H
#define TIME_SERIES_STORE_H

/* WARNING: this file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define TS_OK 0

#define TS_ERR_NULL_POINTER 1

#define TS_ERR_INVALID_UTF8 2

#define TS_ERR_INVALID_PARAMETER 3

#define TS_ERR_NOT_FOUND 4

#define TS_ERR_DUPLICATE 5

#define TS_ERR_INTEGRITY 6

#define TS_ERR_READ_ONLY 7

#define TS_ERR_IO 8

#define TS_ERR_INTERNAL 99

/**
 * Request-only `ts_type` sentinel for the `AbstractDeterministic` family. It is
 * never a stored type and never returned through `out_matched_type`; it only
 * addresses a forecast whose concrete type (`Deterministic` or
 * `DeterministicSingleTimeSeries`) the caller does not need to know in advance.
 */
#define TS_TYPE_ABSTRACT_DETERMINISTIC 100

/**
 * Accumulates pending add requests for a single all-or-nothing
 * `ts_store_add_batch` call. Building the batch performs no store I/O.
 */
typedef struct TsBatch TsBatch;

/**
 * Opaque handle wrapping a core `ForecastReader` (one forecast type, per-key
 * windows).
 */
typedef struct TsForecastReaderHandle TsForecastReaderHandle;

typedef struct TsKey TsKey;

/**
 * Opaque handle wrapping a core `StaticReader` (SingleTimeSeries, columnar).
 */
typedef struct TsStaticReaderHandle TsStaticReaderHandle;

typedef struct TsStore TsStore;

/**
 * Initialize the Rust tracing subscriber.
 *
 * `filter` is a null-terminated UTF-8 [`EnvFilter`] directive string, e.g.
 * `"debug"` or `"time_series_store_core=debug"`. Pass `NULL` to read the
 * `RUST_LOG` environment variable (or emit nothing if the variable is unset).
 *
 * The subscriber is initialized at most once per process. Subsequent calls
 * are no-ops. Returns `TS_OK` on success, `TS_ERR_INVALID_UTF8` if `filter`
 * is not valid UTF-8, or `TS_ERR_INVALID_PARAMETER` if `filter` contains an
 * invalid directive (e.g. an unrecognised level name).
 *
 * # Safety
 *
 * `filter` must be a valid null-terminated UTF-8 string or `NULL`.
 */
int32_t ts_store_init_logging(const char *filter);

/**
 * Create a time-series store and return an owning handle through `out`.
 *
 * # Safety
 *
 * `out` must be valid for writing one pointer. When non-null, `path` must point to a valid,
 * null-terminated UTF-8 string. The returned handle must be released exactly once with
 * `ts_store_free`.
 */
int32_t ts_store_create(const char *path, bool in_memory, struct TsStore **out);

/**
 * Create a store with an explicit NetCDF compression policy.
 *
 * `compression_kind` selects the filter: `0` = none (uncompressed), `1` =
 * DEFLATE at `deflate_level` (0–9) with byte `shuffle` when non-zero. Any
 * other `compression_kind` is rejected. The policy is ignored for in-memory
 * stores and persisted so later appends reuse it. Equivalent to
 * [`ts_store_create`] with `compression_kind = 1`, level 3, shuffle on.
 *
 * # Safety
 *
 * `out` must be valid for writing one pointer. When non-null, `path` must point to a valid,
 * null-terminated UTF-8 string. The returned handle must be released exactly once with
 * `ts_store_free`.
 */
int32_t ts_store_create_with_compression(const char *path,
                                         bool in_memory,
                                         uint8_t compression_kind,
                                         uint8_t deflate_level,
                                         bool shuffle,
                                         struct TsStore **out);

/**
 * Open an existing time-series store and return an owning handle through `out`.
 *
 * # Safety
 *
 * `path` must point to a valid, null-terminated UTF-8 string, and `out` must be valid for writing
 * one pointer. The returned handle must be released exactly once with `ts_store_free`.
 */
int32_t ts_store_open(const char *path, bool read_only, struct TsStore **out);

/**
 * Release a store handle returned by `ts_store_create` or `ts_store_open`.
 *
 * # Safety
 *
 * `handle` must be null or a live handle returned by this library that has not already been freed.
 * The handle must not be used after this call.
 */
void ts_store_free(struct TsStore *handle);

/**
 * Add a SingleTimeSeries to the store.
 *
 * `features_json`, when non-null, is parsed as a JSON object whose values must be int, float, or
 * bool. `logical_type` and `units` are optional.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required string
 * pointers must reference null-terminated UTF-8 strings; optional string pointers may be null.
 * `dims_ptr` must reference `ndims` elements when `ndims` is nonzero, and `data_ptr` must reference
 * `data_byte_len` bytes. `out_key` must be valid for writing one pointer. The returned key must be
 * released with `ts_key_free`.
 */
int32_t ts_store_add_single(struct TsStore *handle,
                            int64_t owner_id,
                            const char *owner_type,
                            int32_t owner_category,
                            const char *name,
                            int64_t initial_ts_unix_ms,
                            int64_t resolution_ms,
                            int32_t dtype,
                            uint64_t ndims,
                            const uint64_t *dims_ptr,
                            const uint8_t *data_ptr,
                            uint64_t data_byte_len,
                            const char *logical_type,
                            const char *features_json,
                            const char *units,
                            struct TsKey **out_key);

/**
 * Add a NonSequentialTimeSeries to the store.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required string
 * pointers must reference null-terminated UTF-8 strings; optional string pointers may be null.
 * `timestamps_unix_ms` must reference `timestamps_len` elements, `dims_ptr` must reference `ndims`
 * elements when `ndims` is nonzero, and `data_ptr` must reference `data_byte_len` bytes. `out_key`
 * must be valid for writing one pointer. The returned key must be released with `ts_key_free`.
 */
int32_t ts_store_add_non_sequential(struct TsStore *handle,
                                    int64_t owner_id,
                                    const char *owner_type,
                                    int32_t owner_category,
                                    const char *name,
                                    const int64_t *timestamps_unix_ms,
                                    uint64_t timestamps_len,
                                    int32_t dtype,
                                    uint64_t ndims,
                                    const uint64_t *dims_ptr,
                                    const uint8_t *data_ptr,
                                    uint64_t data_byte_len,
                                    const char *logical_type,
                                    const char *features_json,
                                    const char *units,
                                    struct TsKey **out_key);

/**
 * Fetch a SingleTimeSeries by key in its native dtype and shape.
 *
 * `out_dtype` receives the element dtype code (see [`ts_type_from_int`]'s dtype
 * siblings: f64=0, f32=1, i64=2, i32=3, u64=4, bool=5). `out_shape` /
 * `out_shape_len` return the full array shape `[length, *element_shape]` (the
 * first dim is time); `out_data` / `out_data_byte_len` return the raw
 * little-endian element bytes. The caller owns both buffers and must free
 * `*out_shape` with `ts_buffer_free_i64` and `*out_data` with
 * `ts_buffer_free_u8`, each using its returned length.
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library. Every output pointer must be
 * valid for writing its indicated value. The returned shape and data buffers must each be released
 * exactly once with the matching free function and returned length.
 */
int32_t ts_store_get_single(const struct TsStore *handle,
                            const struct TsKey *key,
                            int64_t *out_initial_ts_unix_ms,
                            int64_t *out_resolution_ms,
                            int32_t *out_dtype,
                            int64_t **out_shape,
                            uint64_t *out_shape_len,
                            uint8_t **out_data,
                            uint64_t *out_data_byte_len);

/**
 * Fetch a NonSequentialTimeSeries by key.
 *
 * The caller owns both output buffers and must release them with
 * `ts_buffer_free_i64` and `ts_buffer_free_u8`.
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library. Every output pointer must be
 * valid for writing its indicated value. Returned buffers must each be released exactly once with
 * the matching free function and returned length.
 */
int32_t ts_store_get_non_sequential(const struct TsStore *handle,
                                    const struct TsKey *key,
                                    int64_t **out_timestamps,
                                    uint64_t *out_timestamps_len,
                                    int32_t *out_dtype,
                                    uint8_t **out_data,
                                    uint64_t *out_data_byte_len);

/**
 * Remove the time series identified by `key`.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and `key` must be a live key handle created by this
 * library. Neither handle may be concurrently mutated for the duration of the call.
 */
int32_t ts_store_remove(struct TsStore *handle, const struct TsKey *key);

/**
 * Report whether the store contains the time series identified by `key`.
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library, and `out_present` must be valid
 * for writing one `bool`.
 */
int32_t ts_store_has(const struct TsStore *handle, const struct TsKey *key, bool *out_present);

/**
 * Return aggregate time-series counts.
 *
 * # Safety
 *
 * `handle` must be a live store handle. All output pointers must be valid for writing one `i64`.
 */
int32_t ts_store_counts(const struct TsStore *handle,
                        int64_t *out_components_with_time_series,
                        int64_t *out_static_time_series,
                        int64_t *out_forecasts);

/**
 * Write the store's forecast parameters, optionally restricted to forecasts
 * with `filter_resolution_ms` and/or `filter_interval_ms` (`<= 0` = no filter).
 *
 * `out_present` is set to `true` when a matching forecast exists, `false`
 * otherwise. Each of `out_horizon_ms`, `out_interval_ms`, `out_count`,
 * `out_resolution_ms`, and `out_initial_ms` (the initial timestamp as unix ms)
 * receives the corresponding value, or `-1` when that field is absent
 * (durations, resolution, and counts are always non-negative when present, so
 * `-1` is an unambiguous "unset" sentinel).
 *
 * # Safety
 *
 * `handle` must be a live store handle; the filter args are plain scalars.
 * `out_present` must be valid for writing one `bool`; every other output pointer
 * must be valid for writing one `i64`.
 */
int32_t ts_store_get_forecast_parameters(const struct TsStore *handle,
                                         int64_t filter_resolution_ms,
                                         int64_t filter_interval_ms,
                                         bool *out_present,
                                         int64_t *out_horizon_ms,
                                         int64_t *out_interval_ms,
                                         int64_t *out_count,
                                         int64_t *out_resolution_ms,
                                         int64_t *out_initial_ms);

/**
 * Verify all `SingleTimeSeries` share one `(initial_timestamp, length)`.
 *
 * `out_present` is `false` when the store has no `SingleTimeSeries`; otherwise
 * `true` and `out_initial_ms` / `out_length` receive the shared pair. Returns an
 * error when more than one distinct pair exists (the catalog is inconsistent).
 *
 * # Safety
 *
 * `handle` must be a live store handle. Each out pointer must be valid for one
 * write.
 */
int32_t ts_store_check_static_consistency(const struct TsStore *handle,
                                          bool *out_present,
                                          int64_t *out_initial_ms,
                                          int64_t *out_length);

/**
 * List the distinct resolutions present in the store as a JSON array of integer
 * milliseconds (ascending). When `has_time_series_type` is true the listing is
 * restricted to that `TS_TYPE_*` code; otherwise all types are considered.
 *
 * Follows the probe-then-fetch convention: call with `buf` null and `cap` 0 to
 * learn the byte length via `out_len`, then again with a buffer of at least
 * `len + 1` bytes.
 *
 * # Safety
 *
 * `handle` must be a live store handle; the type filter args are plain scalars.
 * `out_len` must be writable; `buf` must be null or valid for `cap` bytes.
 */
int32_t ts_store_get_resolutions(const struct TsStore *handle,
                                 bool has_time_series_type,
                                 int32_t time_series_type,
                                 char *buf,
                                 uint64_t cap,
                                 uint64_t *out_len);

/**
 * Association count grouped by time series type, as a JSON array of
 * `{"time_series_type": <name>, "count": <n>}` objects. Probe-then-fetch (see
 * `ts_store_list_keys`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_len` must be writable; `buf` must be
 * null or valid for `cap` bytes.
 */
int32_t ts_store_counts_by_type(const struct TsStore *handle,
                                char *buf,
                                uint64_t cap,
                                uint64_t *out_len);

/**
 * Write the number of distinct stored arrays (content hashes); shared series
 * count once.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_count` must be valid for writing one
 * `i64`.
 */
int32_t ts_store_num_distinct_arrays(const struct TsStore *handle, int64_t *out_count);

/**
 * Write the detailed counts: distinct owners per category and distinct stored
 * arrays per kind (static vs forecast).
 *
 * # Safety
 *
 * `handle` must be a live store handle. Each out pointer must be valid for
 * writing one `i64`.
 */
int32_t ts_store_counts_detailed(const struct TsStore *handle,
                                 int64_t *out_components,
                                 int64_t *out_supplemental_attributes,
                                 int64_t *out_static_time_series,
                                 int64_t *out_forecasts);

/**
 * List the distinct owner ids of `owner_category` (`0` = Component, `1` =
 * SupplementalAttribute) that have a time series, as a JSON array of integers.
 * Optionally restricted to one `time_series_type` (`TS_TYPE_*` code, gated by
 * `has_time_series_type`) and/or `resolution_ms` (`<= 0` = no filter).
 * Probe-then-fetch (see `ts_store_list_keys`).
 *
 * # Safety
 *
 * `handle` must be a live store handle; the filter args are plain scalars.
 * `out_len` must be writable; `buf` must be null or valid for `cap` bytes.
 */
int32_t ts_store_list_owner_ids(const struct TsStore *handle,
                                int32_t owner_category,
                                bool has_time_series_type,
                                int32_t time_series_type,
                                int64_t resolution_ms,
                                char *buf,
                                uint64_t cap,
                                uint64_t *out_len);

/**
 * Static-series summary as a JSON array. Each object has `owner_type`,
 * `owner_category`, `time_series_type`, `name`, `initial_timestamp_ms`,
 * `resolution_ms`, `time_step_count`, and `count` (the number of associations in
 * the group); fields that do not apply are `null`. Probe-then-fetch.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_len` must be writable; `buf` must be
 * null or valid for `cap` bytes.
 */
int32_t ts_store_static_summary(const struct TsStore *handle,
                                char *buf,
                                uint64_t cap,
                                uint64_t *out_len);

/**
 * Forecast summary as a JSON array. Each object has `owner_type`,
 * `owner_category`, `time_series_type`, `name`, `initial_timestamp_ms`,
 * `resolution_ms`, `horizon_ms`, `interval_ms`, `window_count`, and `count` (the
 * number of associations in the group); fields that do not apply are `null`.
 * Probe-then-fetch.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_len` must be writable; `buf` must be
 * null or valid for `cap` bytes.
 */
int32_t ts_store_forecast_summary(const struct TsStore *handle,
                                  char *buf,
                                  uint64_t cap,
                                  uint64_t *out_len);

/**
 * Write the store's compression policy.
 *
 * `out_kind` receives `0` (no compression) or `1` (DEFLATE). For DEFLATE,
 * `out_level` (0-9) and `out_shuffle` receive the filter parameters; for no
 * compression they are set to `0` / `false`. This reflects the policy the
 * store was created with, restored from the file when the store was opened
 * (in-memory stores report `0`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_kind` and `out_level` must each be
 * valid for writing one `u8`; `out_shuffle` must be valid for writing one `bool`.
 */
int32_t ts_store_get_compression(const struct TsStore *handle,
                                 uint8_t *out_kind,
                                 uint8_t *out_level,
                                 bool *out_shuffle);

/**
 * Verify store integrity and return the number of detected errors.
 *
 * # Safety
 *
 * `handle` must be a live store handle and `out_error_count` must be valid for writing one `u64`.
 */
int32_t ts_store_verify(const struct TsStore *handle, uint64_t *out_error_count);

/**
 * Compact the store.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and must not be used concurrently for the duration
 * of the call.
 */
int32_t ts_store_compact(struct TsStore *handle);

/**
 * Flush pending store writes.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and must not be used concurrently for the duration
 * of the call.
 */
int32_t ts_store_flush(struct TsStore *handle);

/**
 * Look up a SingleTimeSeries metadata record by attributes. On success the
 * caller's out-params receive the initial timestamp, resolution, length, and
 * the 32-byte content hash (written into the `out_data_hash` buffer, which
 * must have room for 32 bytes). Returns `TS_ERR_NOT_FOUND` if absent.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` and `owner_category` (`0` =
 * Component, `1` = SupplementalAttribute) identify the owner. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. Scalar output pointers must be valid for one
 * value and `out_data_hash` must be valid for 32 bytes.
 */
int32_t ts_store_get_metadata(const struct TsStore *handle,
                              int64_t owner_id,
                              int32_t owner_category,
                              const char *name,
                              int64_t resolution_ms,
                              const char *features_json,
                              int64_t *out_initial_ts_unix_ms,
                              int64_t *out_resolution_ms,
                              uint64_t *out_length,
                              uint8_t *out_data_hash,
                              int32_t *out_dtype,
                              char *out_logical_type,
                              uint64_t logical_type_cap,
                              uint64_t *out_logical_type_len);

/**
 * True iff a SingleTimeSeries with the given attributes exists.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` and `owner_category` (`0` =
 * Component, `1` = SupplementalAttribute) identify the owner. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. `out_present` must be valid for writing one
 * `bool`.
 */
int32_t ts_store_has_by_attrs(const struct TsStore *handle,
                              int64_t owner_id,
                              int32_t owner_category,
                              const char *name,
                              int64_t resolution_ms,
                              const char *features_json,
                              bool *out_present);

/**
 * True iff `owner_id` has any time series, optionally filtered to a single
 * time series type (`use_type` selects whether `ts_type` is applied). Answers
 * the name-less `has_time_series(owner)` / `has_time_series(owner, T)` queries.
 *
 * # Safety
 *
 * `handle` must be a live store handle; `owner_id` is a plain integer and
 * `owner_category` (`0` = Component, `1` = SupplementalAttribute) identifies the
 * owner category; `out_present` valid for writing one bool.
 */
int32_t ts_store_has_for_owner(const struct TsStore *handle,
                               int64_t owner_id,
                               int32_t owner_category,
                               int32_t ts_type,
                               bool use_type,
                               bool *out_present);

/**
 * Remove a SingleTimeSeries by attributes. Drops the underlying array iff no
 * other association still references its content hash.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` and `owner_category`
 * (`0` = Component, `1` = SupplementalAttribute) identify the owner. Required strings
 * must be null-terminated UTF-8, and `features_json` may be null.
 */
int32_t ts_store_remove_by_attrs(struct TsStore *handle,
                                 int64_t owner_id,
                                 int32_t owner_category,
                                 const char *name,
                                 int64_t resolution_ms,
                                 const char *features_json);

/**
 * Fetch a stored array by its 32-byte content hash. On success the caller owns
 * `*out_data` and must free it with `ts_buffer_free_u8`.
 *
 * # Safety
 *
 * `handle` must be a live store handle, `data_hash` must reference 32 readable bytes, and every
 * output pointer must be valid for writing its indicated value. The returned buffer must be
 * released exactly once with `ts_buffer_free_u8` using the returned byte length.
 */
int32_t ts_store_get_array_by_hash(const struct TsStore *handle,
                                   const uint8_t *data_hash,
                                   int32_t *out_dtype,
                                   uint8_t **out_data,
                                   uint64_t *out_byte_len);

/**
 * Count `SingleTimeSeries` and `DeterministicSingleTimeSeries` associations
 * that reference the 32-byte content hash `data_hash`, across all owners,
 * writing the counts to `*out_sts` and `*out_dst`. A binding uses these to
 * decide whether removing a `SingleTimeSeries` would orphan a DST that shares
 * its underlying array — a single catalog query rather than a full scan in the
 * caller.
 *
 * # Safety
 *
 * - `handle` must be a live, non-null store handle created by this library; no
 *   concurrent mutation is permitted for the duration of the call.
 * - `data_hash` must be non-null and point to at least 32 readable bytes.
 * - `out_sts` and `out_dst` must each be valid for writing one `u64`.
 */
int32_t ts_store_count_array_references(const struct TsStore *handle,
                                        const uint8_t *data_hash,
                                        uint64_t *out_sts,
                                        uint64_t *out_dst);

/**
 * Add a dense forecast. `data_ptr`/`data_byte_len` is the flattened storage
 * array (Deterministic: `[H, count, *E]`; Scenarios: `[scenario_count, H,
 * count, *E]`). `ts_type` must be 2=Deterministic or 5=Scenarios;
 * `DeterministicSingleTimeSeries` is not directly addable and is derived from a
 * stored `SingleTimeSeries` via `ts_store_transform_single_time_series`.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required strings
 * must be null-terminated UTF-8; optional strings may be null. `data_ptr` must reference `data_len`
 * elements and `out_key` must be valid for writing one pointer. The returned key must be released
 * with `ts_key_free`.
 */
int32_t ts_store_add_forecast(struct TsStore *handle,
                              int64_t owner_id,
                              const char *owner_type,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t initial_ts_unix_ms,
                              int64_t resolution_ms,
                              int64_t horizon_ms,
                              int64_t interval_ms,
                              uint64_t count,
                              int32_t dtype,
                              uint64_t ndims,
                              const uint64_t *dims_ptr,
                              const uint8_t *data_ptr,
                              uint64_t data_byte_len,
                              const char *logical_type,
                              const char *features_json,
                              const char *units,
                              struct TsKey **out_key);

/**
 * Add a `Probabilistic` forecast. `data` is the flattened 3-D storage array
 * `(percentile_count, horizon_count, count)` column-major; `percentiles` is the
 * percentile vector.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required strings
 * must be null-terminated UTF-8; optional strings may be null. `percentiles_ptr` and `data_ptr`
 * must reference their respective element counts, and `out_key` must be valid for writing one
 * pointer. The returned key must be released with `ts_key_free`.
 */
int32_t ts_store_add_probabilistic(struct TsStore *handle,
                                   int64_t owner_id,
                                   const char *owner_type,
                                   int32_t owner_category,
                                   const char *name,
                                   int64_t initial_ts_unix_ms,
                                   int64_t resolution_ms,
                                   int64_t horizon_ms,
                                   int64_t interval_ms,
                                   uint64_t count,
                                   const double *percentiles_ptr,
                                   uint64_t percentiles_len,
                                   int32_t dtype,
                                   uint64_t ndims,
                                   const uint64_t *dims_ptr,
                                   const uint8_t *data_ptr,
                                   uint64_t data_byte_len,
                                   const char *logical_type,
                                   const char *features_json,
                                   const char *units,
                                   struct TsKey **out_key);

/**
 * Create an empty add-batch. Building a batch performs no store I/O.
 *
 * # Safety
 *
 * The returned handle must be released exactly once with `ts_batch_free`
 * (regardless of whether it was submitted via `ts_store_add_batch`).
 */
struct TsBatch *ts_batch_new(void);

/**
 * Free a batch handle created by `ts_batch_new`.
 *
 * # Safety
 *
 * `batch` must be null or a handle returned by `ts_batch_new` that has not
 * already been freed.
 */
void ts_batch_free(struct TsBatch *batch);

/**
 * Append a SingleTimeSeries to a batch. Arguments match
 * `ts_store_add_single` (minus the store handle and `out_key`); the data is
 * copied into the batch, so the caller's buffers need only stay valid for
 * this call.
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `dims_ptr` must reference `ndims` elements when `ndims`
 * is nonzero, and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_single(struct TsBatch *batch,
                            int64_t owner_id,
                            const char *owner_type,
                            int32_t owner_category,
                            const char *name,
                            int64_t initial_ts_unix_ms,
                            int64_t resolution_ms,
                            int32_t dtype,
                            uint64_t ndims,
                            const uint64_t *dims_ptr,
                            const uint8_t *data_ptr,
                            uint64_t data_byte_len,
                            const char *logical_type,
                            const char *features_json,
                            const char *units);

/**
 * Append a NonSequentialTimeSeries to a batch. Arguments match
 * `ts_store_add_non_sequential` (minus the store handle and `out_key`).
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `timestamps_unix_ms` must reference `timestamps_len`
 * elements, `dims_ptr` must reference `ndims` elements when `ndims` is nonzero,
 * and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_non_sequential(struct TsBatch *batch,
                                    int64_t owner_id,
                                    const char *owner_type,
                                    int32_t owner_category,
                                    const char *name,
                                    const int64_t *timestamps_unix_ms,
                                    uint64_t timestamps_len,
                                    int32_t dtype,
                                    uint64_t ndims,
                                    const uint64_t *dims_ptr,
                                    const uint8_t *data_ptr,
                                    uint64_t data_byte_len,
                                    const char *logical_type,
                                    const char *features_json,
                                    const char *units);

/**
 * Append a dense forecast (`ts_type` 2=Deterministic or 5=Scenarios) to a
 * batch. Arguments match `ts_store_add_forecast` (minus the store handle and
 * `out_key`).
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `dims_ptr` must reference `ndims` elements when `ndims`
 * is nonzero, and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_forecast(struct TsBatch *batch,
                              int64_t owner_id,
                              const char *owner_type,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t initial_ts_unix_ms,
                              int64_t resolution_ms,
                              int64_t horizon_ms,
                              int64_t interval_ms,
                              uint64_t count,
                              int32_t dtype,
                              uint64_t ndims,
                              const uint64_t *dims_ptr,
                              const uint8_t *data_ptr,
                              uint64_t data_byte_len,
                              const char *logical_type,
                              const char *features_json,
                              const char *units);

/**
 * Append a `Probabilistic` forecast to a batch. Arguments match
 * `ts_store_add_probabilistic` (minus the store handle and `out_key`).
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `percentiles_ptr` must reference `percentiles_len`
 * elements, `dims_ptr` must reference `ndims` elements when `ndims` is nonzero,
 * and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_probabilistic(struct TsBatch *batch,
                                   int64_t owner_id,
                                   const char *owner_type,
                                   int32_t owner_category,
                                   const char *name,
                                   int64_t initial_ts_unix_ms,
                                   int64_t resolution_ms,
                                   int64_t horizon_ms,
                                   int64_t interval_ms,
                                   uint64_t count,
                                   const double *percentiles_ptr,
                                   uint64_t percentiles_len,
                                   int32_t dtype,
                                   uint64_t ndims,
                                   const uint64_t *dims_ptr,
                                   const uint8_t *data_ptr,
                                   uint64_t data_byte_len,
                                   const char *logical_type,
                                   const char *features_json,
                                   const char *units);

/**
 * Submit every request in `batch` through one all-or-nothing bulk add. On
 * success, writes an array of key handles (input order) to `out_keys` /
 * `out_len`. The batch is drained by this call in all cases — on error
 * nothing was committed and the batch is left empty; rebuild it before
 * retrying.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and `batch` a live batch
 * handle. `out_keys` and `out_len` must each be valid for writing one value.
 * On success the caller owns the returned array and every key handle in it:
 * release each key with `ts_key_free`, then the array buffer itself with
 * `ts_keys_buffer_free(*out_keys, *out_len)` (the same contract as
 * `ts_store_get_time_series_keys`).
 */
int32_t ts_store_add_batch(struct TsStore *handle,
                           struct TsBatch *batch,
                           struct TsKey ***out_keys,
                           uint64_t *out_len);

/**
 * Derive `DeterministicSingleTimeSeries` forecasts from the stored
 * `SingleTimeSeries` associations (see `Store::transform_single_time_series`).
 * Writes the number of series transformed to `*out_count`.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and `out_count` must be valid
 * for writing one `u64`.
 */
int32_t ts_store_transform_single_time_series(struct TsStore *handle,
                                              int64_t horizon_ms,
                                              int64_t interval_ms,
                                              int32_t owner_category,
                                              int64_t resolution_ms,
                                              uint64_t *out_count);

/**
 * Read `Probabilistic` metadata. Like `ts_store_get_forecast_metadata` but also
 * returns the percentiles vector in `*out_percentiles` (caller frees with
 * `ts_buffer_free_f64`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` and `owner_category` (`0` =
 * Component, `1` = SupplementalAttribute) identify the owner. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. Scalar output pointers must each be valid for
 * one value, `out_data_hash` must be valid for 32 bytes, and `out_percentiles` must be valid for
 * writing one pointer. The returned percentile buffer must be released exactly once with
 * `ts_buffer_free_f64` using the returned length.
 */
int32_t ts_store_get_probabilistic_metadata(const struct TsStore *handle,
                                            int64_t owner_id,
                                            int32_t owner_category,
                                            const char *name,
                                            int64_t resolution_ms,
                                            const char *features_json,
                                            int64_t *out_initial_ts_unix_ms,
                                            int64_t *out_resolution_ms,
                                            int64_t *out_horizon_ms,
                                            int64_t *out_interval_ms,
                                            uint64_t *out_count,
                                            uint64_t *out_length,
                                            uint8_t *out_data_hash,
                                            double **out_percentiles,
                                            uint64_t *out_percentiles_len);

/**
 * Read forecast metadata by attributes. Out-params receive initial timestamp,
 * resolution, horizon, interval, count, the stored array length, and the
 * 32-byte content hash (into `out_data_hash`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` and `owner_category` (`0` =
 * Component, `1` = SupplementalAttribute) identify the owner. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. Scalar output pointers must each be valid for
 * one value and `out_data_hash` must be valid for 32 bytes.
 */
int32_t ts_store_get_forecast_metadata(const struct TsStore *handle,
                                       int64_t owner_id,
                                       int32_t owner_category,
                                       const char *name,
                                       int32_t ts_type,
                                       int64_t resolution_ms,
                                       const char *features_json,
                                       int64_t *out_initial_ts_unix_ms,
                                       int64_t *out_resolution_ms,
                                       int64_t *out_horizon_ms,
                                       int64_t *out_interval_ms,
                                       uint64_t *out_count,
                                       uint64_t *out_length,
                                       uint8_t *out_data_hash,
                                       char *logical_type_buf,
                                       uint64_t logical_type_cap,
                                       uint64_t *out_logical_type_len);

/**
 * Fetch a forecast by attributes and return the full data array plus metadata.
 *
 * `ts_type` is a read request: a concrete type (`2`=Deterministic,
 * `3`=DeterministicSingleTimeSeries, `4`=Probabilistic, `5`=Scenarios) or the
 * `TS_TYPE_ABSTRACT_DETERMINISTIC` (`100`) family, which matches a stored
 * `Deterministic` *or* `DeterministicSingleTimeSeries`. The catalog resolves the
 * family authoritatively — no client-side guess-and-retry — and writes the
 * concrete type that matched to `*out_matched_type`. An ambiguous family request
 * (both concrete types share the identity) returns `TS_ERR_INVALID_PARAMETER`;
 * a genuine miss returns the unmasked not-found error.
 *
 * Reads a `Deterministic`, `Probabilistic`, or `Scenarios` forecast (DST is
 * synthesized into `Deterministic`). On success, the caller owns two heap
 * buffers and must free them with the matching deallocators:
 *
 * - `*out_data` (byte buffer, `*out_data_byte_len` bytes) —
 *   free with `ts_buffer_free_u8(*out_data, *out_data_byte_len)`.
 * - `*out_dims` (array of `u64`, `*out_ndims` elements) —
 *   free with `ts_buffer_free_u64(*out_dims, *out_ndims)`.
 * - `*out_percentiles` (`f64` array, `*out_percentiles_len` elements) —
 *   non-NULL only for `Probabilistic`; free with
 *   `ts_buffer_free_f64(*out_percentiles, *out_percentiles_len)`.
 *
 * **Optional time-range / window selection:** when `time_range_present` is
 * `true`, only the windows whose start timestamp falls in
 * `[time_range_start_ms, time_range_end_ms)` are returned. Pass
 * `time_range_present = false` to retrieve all windows.
 *
 * # Safety
 *
 * - `handle` must be a live, non-null store handle created by this library.
 *   No concurrent mutation is permitted for the duration of the call.
 * - `owner_id` and `owner_category` (`0` = Component, `1` = SupplementalAttribute)
 *   identify the owner. `name` must point to a valid, null-terminated
 *   UTF-8 string for the duration of the call; `features_json` may be null.
 * - All `out_*` scalar pointers, including `out_matched_type`, must be valid
 *   for writing one value each.
 * - `out_dims` must be valid for writing one pointer; the returned pointer
 *   must be freed exactly once with `ts_buffer_free_u64` using `*out_ndims`.
 * - `out_data` must be valid for writing one pointer; the returned pointer
 *   must be freed exactly once with `ts_buffer_free_u8` using
 *   `*out_data_byte_len`.
 * - `out_percentiles` must be valid for writing one pointer; when the result
 *   is not `Probabilistic` the pointer is set to null and `*out_percentiles_len`
 *   to 0, so no free is needed. When non-null it must be freed exactly once
 *   with `ts_buffer_free_f64` using `*out_percentiles_len`.
 * - All returned heap buffers are invalidated after their matching free call
 *   and must not be used afterwards.
 */
int32_t ts_store_get_forecast(const struct TsStore *handle,
                              int64_t owner_id,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t resolution_ms,
                              const char *features_json,
                              bool time_range_present,
                              int64_t time_range_start_ms,
                              int64_t time_range_end_ms,
                              int64_t *out_initial_ts_unix_ms,
                              int64_t *out_resolution_ms,
                              int64_t *out_horizon_ms,
                              int64_t *out_interval_ms,
                              uint64_t *out_count,
                              uint64_t *out_scenario_count,
                              uint64_t *out_ndims,
                              uint64_t **out_dims,
                              int32_t *out_dtype,
                              uint8_t **out_data,
                              uint64_t *out_data_byte_len,
                              double **out_percentiles,
                              uint64_t *out_percentiles_len,
                              int32_t *out_matched_type);

/**
 * Fetch a forecast (`Deterministic` / `Probabilistic` / `Scenarios`, or a
 * `DeterministicSingleTimeSeries` synthesized into a `Deterministic`) by key.
 *
 * This is the key-based counterpart to [`ts_store_get_forecast`]: the time
 * series type comes from `key` rather than an explicit `ts_type` argument. The
 * outputs and buffer-ownership rules are identical to [`ts_store_get_forecast`];
 * `*out_matched_type` is set from the key's type (no family resolution needed
 * because the key already names the concrete type).
 *
 * # Safety
 *
 * - `handle` and `key` must be live handles created by this library; no
 *   concurrent mutation is permitted for the duration of the call.
 * - All `out_*` scalar pointers, including `out_matched_type`, must be valid
 *   for writing one value each.
 * - `out_dims` must be valid for writing one pointer; the returned pointer must
 *   be freed exactly once with `ts_buffer_free_u64` using `*out_ndims`.
 * - `out_data` must be valid for writing one pointer; the returned pointer must
 *   be freed exactly once with `ts_buffer_free_u8` using `*out_data_byte_len`.
 * - `out_percentiles` must be valid for writing one pointer; when the result is
 *   not `Probabilistic` the pointer is set to null and `*out_percentiles_len`
 *   to 0, so no free is needed. When non-null it must be freed exactly once
 *   with `ts_buffer_free_f64` using `*out_percentiles_len`.
 */
int32_t ts_store_get_forecast_by_key(const struct TsStore *handle,
                                     const struct TsKey *key,
                                     bool time_range_present,
                                     int64_t time_range_start_ms,
                                     int64_t time_range_end_ms,
                                     int64_t *out_initial_ts_unix_ms,
                                     int64_t *out_resolution_ms,
                                     int64_t *out_horizon_ms,
                                     int64_t *out_interval_ms,
                                     uint64_t *out_count,
                                     uint64_t *out_scenario_count,
                                     uint64_t *out_ndims,
                                     uint64_t **out_dims,
                                     int32_t *out_dtype,
                                     uint8_t **out_data,
                                     uint64_t *out_data_byte_len,
                                     double **out_percentiles,
                                     uint64_t *out_percentiles_len,
                                     int32_t *out_matched_type);

/**
 * Construct a `TimeSeriesKey` handle from attributes `(owner_id, name,
 * ts_type, resolution, features)`.
 *
 * The returned key can be passed to the key-based read functions (e.g.
 * [`ts_store_get_single`], [`ts_store_get_non_sequential`],
 * [`ts_store_get_forecast_by_key`]); it lets an attribute-addressed caller
 * reuse the key-based read path without an `add`/lookup round trip.
 * `resolution_ms <= 0` means "unspecified".
 *
 * # Safety
 *
 * `owner_id` and `owner_category` (`0` = Component, `1` = SupplementalAttribute)
 * identify the owner. `name` must point to a valid, null-terminated
 * UTF-8 string. `features_json`, when non-null, must be a null-terminated UTF-8
 * JSON object. `out_key` must be valid for writing one pointer. The returned key
 * must be released exactly once with `ts_key_free`.
 */
int32_t ts_make_key_from_attrs(int64_t owner_id,
                               int32_t owner_category,
                               const char *name,
                               int32_t ts_type,
                               int64_t resolution_ms,
                               const char *features_json,
                               struct TsKey **out_key);

/**
 * List every time series key associated with `owner_id`. On success
 * `*out_keys` points to an array of `*out_len` owned key handles (one per
 * association, including derived `DeterministicSingleTimeSeries` rows), each
 * usable with the key-based read functions.
 *
 * Ownership is two-tiered: free every individual `TsKey` with `ts_key_free`,
 * then free the array buffer itself with `ts_keys_buffer_free`. When the owner
 * has no series, `*out_keys` is set to null and `*out_len` to 0 (no free
 * needed).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` and `owner_category` (`0` =
 * Component, `1` = SupplementalAttribute) identify the owner.
 * `out_keys` must be valid for writing one pointer and `out_len` for writing one
 * `u64`.
 */
int32_t ts_store_get_time_series_keys(const struct TsStore *handle,
                                      int64_t owner_id,
                                      int32_t owner_category,
                                      struct TsKey ***out_keys,
                                      uint64_t *out_len);

/**
 * List time series keys as a JSON array string (see `keys_to_json` for the
 * per-key shape). Every filter is optional and independent; with none set the
 * whole store is listed. A `has_*` flag of `false` (or a null string pointer)
 * disables that filter:
 * - `owner_id` / `owner_category` (`0` = Component, `1` = SupplementalAttribute)
 * - `time_series_type` (the `TS_TYPE_*` code)
 * - `name` (null = no name filter)
 * - `resolution_ms` (`<= 0` = no resolution filter)
 * - `features_json` (a JSON object; null or empty = no feature filter; matches as
 *   a subset, i.e. a key whose features include all the given ones)
 *
 * Follows the probe-then-fetch convention: call with `buf` null and `cap` 0 to
 * learn the byte length via `out_len`, then call again with a buffer of at
 * least `len + 1` bytes. The string is NUL-terminated and truncated to `cap`;
 * `out_len` is always the untruncated byte length.
 *
 * # Safety
 *
 * `handle` must be a live store handle. The scalar filter flags/values are plain
 * scalars. `name` and `features_json` must each be null or a null-terminated
 * UTF-8 string. `out_len` must be writable; `buf` must be null or valid for
 * `cap` bytes.
 */
int32_t ts_store_list_keys(const struct TsStore *handle,
                           bool has_owner,
                           int64_t owner_id,
                           bool has_owner_category,
                           int32_t owner_category,
                           bool has_time_series_type,
                           int32_t time_series_type,
                           const char *name,
                           int64_t resolution_ms,
                           const char *features_json,
                           char *buf,
                           uint64_t cap,
                           uint64_t *out_len);

/**
 * Free the key-handle array returned by `ts_store_get_time_series_keys`.
 *
 * This releases only the array buffer, not the keys it held: transfer each
 * `TsKey` out first (the Julia binding wraps each in a finalized object) and
 * release them individually with `ts_key_free`.
 *
 * # Safety
 *
 * `ptr` must be null or an array returned by `ts_store_get_time_series_keys`
 * with exactly `len` elements, not previously freed. It must not be used after
 * this call.
 */
void ts_keys_buffer_free(struct TsKey **ptr, uint64_t len);

/**
 * Read the attributes of a key handle: its time series type code (see
 * `ts_type_from_int`), resolution in milliseconds (`0` when unset), the owner
 * id (an integer), the name string, and the features as a JSON object string
 * (`"{}"` when empty — the same shape the attribute-addressed entry points
 * accept).
 *
 * `out_owner_id` receives the owner id directly. The `name` and `features`
 * strings follow the probe-then-fetch convention: call with `name_buf` /
 * `features_buf` null (and capacities `0`) to learn the required lengths via the
 * matching `out_*_len`, then call again with buffers of at least `len + 1`
 * bytes. Each returned string is NUL-terminated and truncated to its capacity;
 * the reported length is always the untruncated byte length.
 *
 * # Safety
 *
 * `key` must be a live key handle created by this library. `out_type`,
 * `out_resolution_ms`, `out_owner_id`, `out_owner_category`, `out_name_len`, and
 * `out_features_len` must each be valid for writing one value. `out_owner_category`
 * receives `0` (Component) or `1` (SupplementalAttribute). `name_buf` /
 * `features_buf` may be null; when non-null they must be valid for writing
 * `name_cap` / `features_cap` bytes respectively.
 */
int32_t ts_key_attributes(const struct TsKey *key,
                          int32_t *out_type,
                          int64_t *out_resolution_ms,
                          int64_t *out_owner_id,
                          int32_t *out_owner_category,
                          char *name_buf,
                          uint64_t name_cap,
                          uint64_t *out_name_len,
                          char *features_buf,
                          uint64_t features_cap,
                          uint64_t *out_features_len);

/**
 * Read an association's `name` by key, resolved through the stored metadata
 * (`Store::get_metadata`). This surfaces the per-association `name` that is not
 * carried on the key itself — the read path uses it to populate the returned
 * time series object.
 *
 * `name` uses the probe-then-fetch convention (see [`ts_key_attributes`]).
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library.
 * `out_name_len` must be valid for writing one `u64`. `name_buf` may be null;
 * when non-null it must be valid for writing `name_cap` bytes.
 */
int32_t ts_store_get_association(const struct TsStore *handle,
                                 const struct TsKey *key,
                                 char *name_buf,
                                 uint64_t name_cap,
                                 uint64_t *out_name_len);

/**
 * Release a `u64` dims buffer returned by `ts_store_get_forecast`.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` elements. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_u64(uint64_t *ptr, uint64_t len);

/**
 * True iff a time series of `ts_type` with the given attributes exists.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` and `owner_category` (`0` =
 * Component, `1` = SupplementalAttribute) identify the owner. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. `out_present` must be valid for writing one
 * `bool`.
 */
int32_t ts_store_has_typed(const struct TsStore *handle,
                           int64_t owner_id,
                           int32_t owner_category,
                           const char *name,
                           int32_t ts_type,
                           int64_t resolution_ms,
                           const char *features_json,
                           bool *out_present);

/**
 * Remove a time series of `ts_type` by attributes.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` and `owner_category`
 * (`0` = Component, `1` = SupplementalAttribute) identify the owner. Required strings
 * must be null-terminated UTF-8, and `features_json` may be null.
 */
int32_t ts_store_remove_typed(struct TsStore *handle,
                              int64_t owner_id,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t resolution_ms,
                              const char *features_json);

/**
 * Remove all time series, or all for a single owner when `has_owner` is true.
 * Returns `TS_OK` on success.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `has_owner`, `owner_id`, and
 * `owner_category` are plain scalars; when `has_owner` is true `owner_category`
 * (`0` = Component, `1` = SupplementalAttribute) scopes the clear to one owner.
 */
int32_t ts_store_clear(struct TsStore *handle,
                       bool has_owner,
                       int64_t owner_id,
                       int32_t owner_category);

/**
 * Reassign every time series owned by `old_owner_id` to `new_owner_id`.
 * When `out_updated` is non-null it receives the number of associations
 * changed. Returns `TS_OK` on success.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `old_owner_id` and
 * `new_owner_id` are plain integers; `owner_category` (`0` = Component, `1` =
 * SupplementalAttribute) identifies the owner category. When non-null,
 * `out_updated` must point to writable `u64` storage.
 */
int32_t ts_store_replace_owner(struct TsStore *handle,
                               int64_t old_owner_id,
                               int64_t new_owner_id,
                               int32_t owner_category,
                               uint64_t *out_updated);

/**
 * Release a key handle returned by this library.
 *
 * # Safety
 *
 * `key` must be null or a live key handle returned by this library that has not already been
 * freed. The key must not be used after this call.
 */
void ts_key_free(struct TsKey *key);

/**
 * Release an `f64` buffer returned by this library.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` elements. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_f64(double *ptr, uint64_t len);

/**
 * Free a `u8` buffer returned by `ts_store_get_array_by_hash`.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` bytes. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_u8(uint8_t *ptr, uint64_t len);

/**
 * Free an `i64` buffer returned by `ts_store_get_non_sequential`.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` elements. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_i64(int64_t *ptr, uint64_t len);

/**
 * Copy the thread-local error message into `buf` (UTF-8, null-terminated).
 * Returns the number of bytes that would have been written (excluding the NUL)
 * in `*needed`. If `buf_len` is too small, `buf` is filled up to its length
 * and truncated; the function still returns `TS_OK` and the caller can decide
 * whether to retry with a larger buffer.
 *
 * # Safety
 *
 * `needed` may be null; otherwise it must be valid for writing one `u64`. `buf` may be null when
 * `buf_len` is zero; otherwise it must reference at least `buf_len` writable bytes.
 */
int32_t ts_last_error_message(char *buf, uint64_t buf_len, uint64_t *needed);

/**
 * Build a [`TsStaticReaderHandle`] over the SingleTimeSeries matching the
 * filter. `resolution_ms` must be positive (one resolution per reader); the
 * matched series must share one grid (`initial_timestamp` + `length`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `name` / `features_json` must be null
 * or valid null-terminated UTF-8. `out_reader` must be valid for writing one
 * pointer; the returned handle must be freed exactly once with
 * `ts_static_reader_free`.
 */
int32_t ts_store_build_static_reader(const struct TsStore *handle,
                                     bool has_owner,
                                     int64_t owner_id,
                                     bool has_owner_category,
                                     int32_t owner_category,
                                     const char *name,
                                     int64_t resolution_ms,
                                     const char *features_json,
                                     struct TsStaticReaderHandle **out_reader);

/**
 * Read the reader's master grid: `initial_timestamp` (unix ms), resolution
 * (ms), and the number of timestamps on the grid.
 *
 * # Safety
 *
 * `reader` must be a live static-reader handle. Each out pointer must be valid
 * for writing one value.
 */
int32_t ts_static_reader_grid(const struct TsStaticReaderHandle *reader,
                              int64_t *out_initial_ms,
                              int64_t *out_resolution_ms,
                              uint64_t *out_length);

/**
 * Number of columnar groups in the reader.
 *
 * # Safety
 *
 * `reader` must be a live static-reader handle. `out_n` must be valid for
 * writing one `u64`.
 */
int32_t ts_static_reader_num_groups(const struct TsStaticReaderHandle *reader, uint64_t *out_n);

/**
 * Read group `group_idx`'s layout: its dtype code, column count, and per-step
 * element shape. The shape follows the probe-then-fetch convention: call with
 * `shape_buf` null / `shape_cap` 0 to learn `out_shape_len`, then call again
 * with a buffer of at least that many `i64` values. An empty shape (scalar per
 * step) reports length 0.
 *
 * # Safety
 *
 * `reader` must be a live static-reader handle. `out_dtype`, `out_num_columns`,
 * and `out_shape_len` must be valid for writing one value each. When non-null,
 * `shape_buf` must be valid for writing `shape_cap` `i64` values.
 */
int32_t ts_static_reader_group_info(const struct TsStaticReaderHandle *reader,
                                    uint64_t group_idx,
                                    int32_t *out_dtype,
                                    uint64_t *out_num_columns,
                                    int64_t *shape_buf,
                                    uint64_t shape_cap,
                                    uint64_t *out_shape_len);

/**
 * Return an owned key handle for column `col_idx` of group `group_idx`. The
 * handle carries the column's identity and must be freed with `ts_key_free`.
 *
 * # Safety
 *
 * `reader` must be a live static-reader handle. `out_key` must be valid for
 * writing one pointer.
 */
int32_t ts_static_reader_group_key(const struct TsStaticReaderHandle *reader,
                                   uint64_t group_idx,
                                   uint64_t col_idx,
                                   struct TsKey **out_key);

/**
 * Read the value of every series at `at_unix_ms`, filling the reader's reusable
 * buffers. After this, `ts_static_reader_group_values` exposes each group's
 * bytes. Errors if `at_unix_ms` is off the reader's grid.
 *
 * # Safety
 *
 * `reader` must be a live static-reader handle and `store` a live store handle.
 */
int32_t ts_static_reader_read(struct TsStaticReaderHandle *reader,
                              const struct TsStore *store,
                              int64_t at_unix_ms);

/**
 * Expose group `group_idx`'s value bytes from the most recent read. The pointer
 * is into reader-owned memory and is valid until the next read on this reader
 * or until it is freed; do not free it. Before any read the length is 0.
 *
 * # Safety
 *
 * `reader` must be a live static-reader handle. `out_ptr` and `out_byte_len`
 * must be valid for writing one value each.
 */
int32_t ts_static_reader_group_values(const struct TsStaticReaderHandle *reader,
                                      uint64_t group_idx,
                                      const uint8_t **out_ptr,
                                      uint64_t *out_byte_len);

/**
 * Free a static-reader handle.
 *
 * # Safety
 *
 * `reader` must be null or a handle from `ts_store_build_static_reader`, not
 * previously freed, and unused after this call.
 */
void ts_static_reader_free(struct TsStaticReaderHandle *reader);

/**
 * Build a [`TsForecastReaderHandle`] over the forecasts matching the filter.
 * `time_series_type` must be a forecast type; a `Deterministic` reader is
 * abstract and also includes `DeterministicSingleTimeSeries`. `resolution_ms`
 * must be positive; matched forecasts must share one window timeline.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `name` / `features_json` must be null
 * or valid null-terminated UTF-8. `out_reader` must be valid for writing one
 * pointer; free the result with `ts_forecast_reader_free`.
 */
int32_t ts_store_build_forecast_reader(const struct TsStore *handle,
                                       bool has_owner,
                                       int64_t owner_id,
                                       bool has_owner_category,
                                       int32_t owner_category,
                                       int32_t time_series_type,
                                       const char *name,
                                       int64_t resolution_ms,
                                       const char *features_json,
                                       struct TsForecastReaderHandle **out_reader);

/**
 * Read the reader's window timeline: `initial_timestamp` (unix ms), resolution
 * (ms), interval (ms), and the window count.
 *
 * # Safety
 *
 * `reader` must be a live forecast-reader handle. Each out pointer must be
 * valid for writing one value.
 */
int32_t ts_forecast_reader_timeline(const struct TsForecastReaderHandle *reader,
                                    int64_t *out_initial_ms,
                                    int64_t *out_resolution_ms,
                                    int64_t *out_interval_ms,
                                    uint64_t *out_count);

/**
 * Number of per-key window entries in the reader.
 *
 * # Safety
 *
 * `reader` must be a live forecast-reader handle. `out_n` must be valid for
 * writing one `u64`.
 */
int32_t ts_forecast_reader_num_entries(const struct TsForecastReaderHandle *reader,
                                       uint64_t *out_n);

/**
 * Read entry `entry_idx`'s layout: its dtype code and window shape. The shape
 * follows the probe-then-fetch convention (call with `shape_buf` null /
 * `shape_cap` 0 to learn `out_shape_len`).
 *
 * # Safety
 *
 * `reader` must be a live forecast-reader handle. `out_dtype` and
 * `out_shape_len` must be valid for writing one value each. When non-null,
 * `shape_buf` must be valid for writing `shape_cap` `i64` values.
 */
int32_t ts_forecast_reader_entry_info(const struct TsForecastReaderHandle *reader,
                                      uint64_t entry_idx,
                                      int32_t *out_dtype,
                                      int64_t *shape_buf,
                                      uint64_t shape_cap,
                                      uint64_t *out_shape_len);

/**
 * Return an owned key handle for entry `entry_idx`, freed with `ts_key_free`.
 *
 * # Safety
 *
 * `reader` must be a live forecast-reader handle. `out_key` must be valid for
 * writing one pointer.
 */
int32_t ts_forecast_reader_entry_key(const struct TsForecastReaderHandle *reader,
                                     uint64_t entry_idx,
                                     struct TsKey **out_key);

/**
 * Read the forecast window at `at_unix_ms` for every entry, filling the
 * reader's reusable buffers. Errors if `at_unix_ms` is off the window timeline.
 *
 * # Safety
 *
 * `reader` must be a live forecast-reader handle and `store` a live store
 * handle.
 */
int32_t ts_forecast_reader_read(struct TsForecastReaderHandle *reader,
                                const struct TsStore *store,
                                int64_t at_unix_ms);

/**
 * Expose entry `entry_idx`'s window bytes from the most recent read. The
 * pointer is into reader-owned memory, valid until the next read or free; do
 * not free it. Before any read the length is 0.
 *
 * # Safety
 *
 * `reader` must be a live forecast-reader handle. `out_ptr` and `out_byte_len`
 * must be valid for writing one value each.
 */
int32_t ts_forecast_reader_entry_values(const struct TsForecastReaderHandle *reader,
                                        uint64_t entry_idx,
                                        const uint8_t **out_ptr,
                                        uint64_t *out_byte_len);

/**
 * Free a forecast-reader handle.
 *
 * # Safety
 *
 * `reader` must be null or a handle from `ts_store_build_forecast_reader`, not
 * previously freed, and unused after this call.
 */
void ts_forecast_reader_free(struct TsForecastReaderHandle *reader);

#endif  /* TIME_SERIES_STORE_H */
