/* Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef TIME_SERIES_STORE_H
#define TIME_SERIES_STORE_H

/* WARNING: this file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define TS_OK 0

#define TS_ERR_NULL_POINTER 1

#define TS_ERR_INVALID_UTF8 2

#define TS_ERR_INVALID_PARAMETER 3

#define TS_ERR_NOT_FOUND 4

#define TS_ERR_DUPLICATE 5

#define TS_ERR_INTEGRITY 6

#define TS_ERR_READ_ONLY 7

#define TS_ERR_IO 8

#define TS_ERR_INTERNAL 99

typedef struct TsKey TsKey;

typedef struct TsStore TsStore;

int32_t ts_store_create(const char *path, bool in_memory, struct TsStore **out);

int32_t ts_store_open(const char *path, bool read_only, struct TsStore **out);

void ts_store_free(struct TsStore *handle);

int32_t ts_store_add_single(struct TsStore *handle,
                            const char *owner_uuid,
                            const char *owner_type,
                            int32_t owner_category,
                            const char *name,
                            int64_t initial_ts_unix_ns,
                            int64_t resolution_ns,
                            int32_t dtype,
                            uint64_t ndims,
                            const uint64_t *dims_ptr,
                            const uint8_t *data_ptr,
                            uint64_t data_byte_len,
                            const char *logical_type,
                            const char *features_json,
                            const char *units,
                            const char *scaling_expr,
                            struct TsKey **out_key);

/**
 * Fetch a SingleTimeSeries by key.
 *
 * On success, the caller owns the buffer pointed to by `*out_data` and must
 * free it with `ts_buffer_free_f64(*out_data, *out_data_len)`.
 */
int32_t ts_store_get_single(const struct TsStore *handle,
                            const struct TsKey *key,
                            int64_t *out_initial_ts_unix_ns,
                            int64_t *out_resolution_ns,
                            double **out_data,
                            uint64_t *out_data_len);

int32_t ts_store_remove(struct TsStore *handle, const struct TsKey *key);

int32_t ts_store_has(const struct TsStore *handle, const struct TsKey *key, bool *out_present);

int32_t ts_store_counts(const struct TsStore *handle,
                        int64_t *out_components_with_time_series,
                        int64_t *out_static_time_series,
                        int64_t *out_forecasts);

int32_t ts_store_verify(const struct TsStore *handle, uint64_t *out_error_count);

int32_t ts_store_compact(struct TsStore *handle);

int32_t ts_store_flush(struct TsStore *handle);

/**
 * Look up a SingleTimeSeries metadata record by attributes. On success the
 * caller's out-params receive the initial timestamp, resolution, length, and
 * the 32-byte content hash (written into the `out_data_hash` buffer, which
 * must have room for 32 bytes). Returns `TS_ERR_NOT_FOUND` if absent.
 */
int32_t ts_store_get_metadata(const struct TsStore *handle,
                              const char *owner_uuid,
                              const char *name,
                              int64_t resolution_ns,
                              const char *features_json,
                              int64_t *out_initial_ts_unix_ns,
                              int64_t *out_resolution_ns,
                              uint64_t *out_length,
                              uint8_t *out_data_hash,
                              int32_t *out_dtype);

/**
 * True iff a SingleTimeSeries with the given attributes exists.
 */
int32_t ts_store_has_by_attrs(const struct TsStore *handle,
                              const char *owner_uuid,
                              const char *name,
                              int64_t resolution_ns,
                              const char *features_json,
                              bool *out_present);

/**
 * Remove a SingleTimeSeries by attributes. Drops the underlying array iff no
 * other association still references its content hash.
 */
int32_t ts_store_remove_by_attrs(struct TsStore *handle,
                                 const char *owner_uuid,
                                 const char *name,
                                 int64_t resolution_ns,
                                 const char *features_json);

/**
 * Fetch a stored array by its 32-byte content hash. On success the caller owns
 * `*out_data` and must free it with `ts_buffer_free_f64`.
 */
int32_t ts_store_get_array_by_hash(const struct TsStore *handle,
                                   const uint8_t *data_hash,
                                   int32_t *out_dtype,
                                   uint8_t **out_data,
                                   uint64_t *out_byte_len);

/**
 * Add a forecast. `data_ptr`/`data_len` is the flattened storage array
 * (Deterministic: `(horizon_count, count)` column-major; DST: the underlying
 * SingleTimeSeries array). `ts_type`: 2=Deterministic, 3=DeterministicSingleTimeSeries.
 */
int32_t ts_store_add_forecast(struct TsStore *handle,
                              const char *owner_uuid,
                              const char *owner_type,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t initial_ts_unix_ns,
                              int64_t resolution_ns,
                              int64_t horizon_ns,
                              int64_t interval_ns,
                              uint64_t count,
                              const double *data_ptr,
                              uint64_t data_len,
                              const char *features_json,
                              const char *units,
                              const char *scaling_expr,
                              struct TsKey **out_key);

/**
 * Add a `Probabilistic` forecast. `data` is the flattened 3-D storage array
 * `(percentile_count, horizon_count, count)` column-major; `percentiles` is the
 * percentile vector.
 */
int32_t ts_store_add_probabilistic(struct TsStore *handle,
                                   const char *owner_uuid,
                                   const char *owner_type,
                                   int32_t owner_category,
                                   const char *name,
                                   int64_t initial_ts_unix_ns,
                                   int64_t resolution_ns,
                                   int64_t horizon_ns,
                                   int64_t interval_ns,
                                   uint64_t count,
                                   const double *percentiles_ptr,
                                   uint64_t percentiles_len,
                                   const double *data_ptr,
                                   uint64_t data_len,
                                   const char *features_json,
                                   const char *units,
                                   const char *scaling_expr,
                                   struct TsKey **out_key);

/**
 * Read `Probabilistic` metadata. Like `ts_store_get_forecast_metadata` but also
 * returns the percentiles vector in `*out_percentiles` (caller frees with
 * `ts_buffer_free_f64`).
 */
int32_t ts_store_get_probabilistic_metadata(const struct TsStore *handle,
                                            const char *owner_uuid,
                                            const char *name,
                                            int64_t resolution_ns,
                                            const char *features_json,
                                            int64_t *out_initial_ts_unix_ns,
                                            int64_t *out_resolution_ns,
                                            int64_t *out_horizon_ns,
                                            int64_t *out_interval_ns,
                                            uint64_t *out_count,
                                            uint64_t *out_length,
                                            uint8_t *out_data_hash,
                                            double **out_percentiles,
                                            uint64_t *out_percentiles_len);

/**
 * Read forecast metadata by attributes. Out-params receive initial timestamp,
 * resolution, horizon, interval, count, the stored array length, and the
 * 32-byte content hash (into `out_data_hash`).
 */
int32_t ts_store_get_forecast_metadata(const struct TsStore *handle,
                                       const char *owner_uuid,
                                       const char *name,
                                       int32_t ts_type,
                                       int64_t resolution_ns,
                                       const char *features_json,
                                       int64_t *out_initial_ts_unix_ns,
                                       int64_t *out_resolution_ns,
                                       int64_t *out_horizon_ns,
                                       int64_t *out_interval_ns,
                                       uint64_t *out_count,
                                       uint64_t *out_length,
                                       uint8_t *out_data_hash);

/**
 * True iff a time series of `ts_type` with the given attributes exists.
 */
int32_t ts_store_has_typed(const struct TsStore *handle,
                           const char *owner_uuid,
                           const char *name,
                           int32_t ts_type,
                           int64_t resolution_ns,
                           const char *features_json,
                           bool *out_present);

/**
 * Remove a time series of `ts_type` by attributes.
 */
int32_t ts_store_remove_typed(struct TsStore *handle,
                              const char *owner_uuid,
                              const char *name,
                              int32_t ts_type,
                              int64_t resolution_ns,
                              const char *features_json);

/**
 * Remove all time series, or all for a single owner when `owner_uuid` is
 * non-null. Returns `TS_OK` on success.
 */
int32_t ts_store_clear(struct TsStore *handle, const char *owner_uuid);

void ts_key_free(struct TsKey *key);

void ts_buffer_free_f64(double *ptr, uint64_t len);

/**
 * Free a `u8` buffer returned by `ts_store_get_array_by_hash`.
 */
void ts_buffer_free_u8(uint8_t *ptr, uint64_t len);

/**
 * Copy the thread-local error message into `buf` (UTF-8, null-terminated).
 * Returns the number of bytes that would have been written (excluding the NUL)
 * in `*needed`. If `buf_len` is too small, `buf` is filled up to its length
 * and truncated; the function still returns `TS_OK` and the caller can decide
 * whether to retry with a larger buffer.
 */
int32_t ts_last_error_message(char *buf, uint64_t buf_len, uint64_t *needed);

#endif  /* TIME_SERIES_STORE_H */
