/* Auto-generated by cbindgen. DO NOT EDIT. */

#ifndef TIME_SERIES_STORE_H
#define TIME_SERIES_STORE_H

/* WARNING: this file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define TS_OK 0

#define TS_ERR_NULL_POINTER 1

#define TS_ERR_INVALID_UTF8 2

#define TS_ERR_INVALID_PARAMETER 3

#define TS_ERR_NOT_FOUND 4

#define TS_ERR_DUPLICATE 5

#define TS_ERR_INTEGRITY 6

#define TS_ERR_READ_ONLY 7

#define TS_ERR_IO 8

#define TS_ERR_INTERNAL 99

/**
 * Accumulates pending add requests for a single all-or-nothing
 * `ts_store_add_batch` call. Building the batch performs no store I/O.
 */
typedef struct TsBatch TsBatch;

typedef struct TsKey TsKey;

typedef struct TsStore TsStore;

/**
 * Initialize the Rust tracing subscriber.
 *
 * `filter` is a null-terminated UTF-8 [`EnvFilter`] directive string, e.g.
 * `"debug"` or `"time_series_store_core=debug"`. Pass `NULL` to read the
 * `RUST_LOG` environment variable (or emit nothing if the variable is unset).
 *
 * The subscriber is initialized at most once per process. Subsequent calls
 * are no-ops. Returns `TS_OK` on success, `TS_ERR_INVALID_UTF8` if `filter`
 * is not valid UTF-8, or `TS_ERR_INVALID_PARAMETER` if `filter` contains an
 * invalid directive (e.g. an unrecognised level name).
 *
 * # Safety
 *
 * `filter` must be a valid null-terminated UTF-8 string or `NULL`.
 */
int32_t ts_store_init_logging(const char *filter);

/**
 * Create a time-series store and return an owning handle through `out`.
 *
 * # Safety
 *
 * `out` must be valid for writing one pointer. When non-null, `path` must point to a valid,
 * null-terminated UTF-8 string. The returned handle must be released exactly once with
 * `ts_store_free`.
 */
int32_t ts_store_create(const char *path, bool in_memory, struct TsStore **out);

/**
 * Create a store with an explicit NetCDF compression policy.
 *
 * `compression_kind` selects the filter: `0` = none (uncompressed), `1` =
 * DEFLATE at `deflate_level` (0–9) with byte `shuffle` when non-zero. Any
 * other `compression_kind` is rejected. The policy is ignored for in-memory
 * stores and persisted so later appends reuse it. Equivalent to
 * [`ts_store_create`] with `compression_kind = 1`, level 3, shuffle on.
 *
 * # Safety
 *
 * `out` must be valid for writing one pointer. When non-null, `path` must point to a valid,
 * null-terminated UTF-8 string. The returned handle must be released exactly once with
 * `ts_store_free`.
 */
int32_t ts_store_create_with_compression(const char *path,
                                         bool in_memory,
                                         uint8_t compression_kind,
                                         uint8_t deflate_level,
                                         bool shuffle,
                                         struct TsStore **out);

/**
 * Open an existing time-series store and return an owning handle through `out`.
 *
 * # Safety
 *
 * `path` must point to a valid, null-terminated UTF-8 string, and `out` must be valid for writing
 * one pointer. The returned handle must be released exactly once with `ts_store_free`.
 */
int32_t ts_store_open(const char *path, bool read_only, struct TsStore **out);

/**
 * Release a store handle returned by `ts_store_create` or `ts_store_open`.
 *
 * # Safety
 *
 * `handle` must be null or a live handle returned by this library that has not already been freed.
 * The handle must not be used after this call.
 */
void ts_store_free(struct TsStore *handle);

/**
 * Add a SingleTimeSeries to the store.
 *
 * `features_json`, when non-null, is parsed as a JSON object whose values must be int, float, or
 * bool. `logical_type` and `units` are optional.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required string
 * pointers must reference null-terminated UTF-8 strings; optional string pointers may be null.
 * `dims_ptr` must reference `ndims` elements when `ndims` is nonzero, and `data_ptr` must reference
 * `data_byte_len` bytes. `out_key` must be valid for writing one pointer. The returned key must be
 * released with `ts_key_free`.
 */
int32_t ts_store_add_single(struct TsStore *handle,
                            int64_t owner_id,
                            const char *owner_type,
                            int32_t owner_category,
                            const char *name,
                            int64_t initial_ts_unix_ms,
                            int64_t resolution_ms,
                            int32_t dtype,
                            uint64_t ndims,
                            const uint64_t *dims_ptr,
                            const uint8_t *data_ptr,
                            uint64_t data_byte_len,
                            const char *logical_type,
                            const char *features_json,
                            const char *units,
                            struct TsKey **out_key);

/**
 * Add a NonSequentialTimeSeries to the store.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required string
 * pointers must reference null-terminated UTF-8 strings; optional string pointers may be null.
 * `timestamps_unix_ms` must reference `timestamps_len` elements, `dims_ptr` must reference `ndims`
 * elements when `ndims` is nonzero, and `data_ptr` must reference `data_byte_len` bytes. `out_key`
 * must be valid for writing one pointer. The returned key must be released with `ts_key_free`.
 */
int32_t ts_store_add_non_sequential(struct TsStore *handle,
                                    int64_t owner_id,
                                    const char *owner_type,
                                    int32_t owner_category,
                                    const char *name,
                                    const int64_t *timestamps_unix_ms,
                                    uint64_t timestamps_len,
                                    int32_t dtype,
                                    uint64_t ndims,
                                    const uint64_t *dims_ptr,
                                    const uint8_t *data_ptr,
                                    uint64_t data_byte_len,
                                    const char *logical_type,
                                    const char *features_json,
                                    const char *units,
                                    struct TsKey **out_key);

/**
 * Fetch a SingleTimeSeries by key.
 *
 * On success, the caller owns the buffer pointed to by `*out_data` and must
 * free it with `ts_buffer_free_f64(*out_data, *out_data_len)`.
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library. Every output pointer must be
 * valid for writing its indicated value. The returned data buffer must be released exactly once
 * with `ts_buffer_free_f64` using the returned length.
 */
int32_t ts_store_get_single(const struct TsStore *handle,
                            const struct TsKey *key,
                            int64_t *out_initial_ts_unix_ms,
                            int64_t *out_resolution_ms,
                            double **out_data,
                            uint64_t *out_data_len);

/**
 * Fetch a NonSequentialTimeSeries by key.
 *
 * The caller owns both output buffers and must release them with
 * `ts_buffer_free_i64` and `ts_buffer_free_u8`.
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library. Every output pointer must be
 * valid for writing its indicated value. Returned buffers must each be released exactly once with
 * the matching free function and returned length.
 */
int32_t ts_store_get_non_sequential(const struct TsStore *handle,
                                    const struct TsKey *key,
                                    int64_t **out_timestamps,
                                    uint64_t *out_timestamps_len,
                                    int32_t *out_dtype,
                                    uint8_t **out_data,
                                    uint64_t *out_data_byte_len);

/**
 * Remove the time series identified by `key`.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and `key` must be a live key handle created by this
 * library. Neither handle may be concurrently mutated for the duration of the call.
 */
int32_t ts_store_remove(struct TsStore *handle, const struct TsKey *key);

/**
 * Report whether the store contains the time series identified by `key`.
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library, and `out_present` must be valid
 * for writing one `bool`.
 */
int32_t ts_store_has(const struct TsStore *handle, const struct TsKey *key, bool *out_present);

/**
 * Return aggregate time-series counts.
 *
 * # Safety
 *
 * `handle` must be a live store handle. All output pointers must be valid for writing one `i64`.
 */
int32_t ts_store_counts(const struct TsStore *handle,
                        int64_t *out_components_with_time_series,
                        int64_t *out_static_time_series,
                        int64_t *out_forecasts);

/**
 * Write the store's forecast parameters.
 *
 * `out_present` is set to `true` when the store holds at least one forecast,
 * `false` otherwise. Each of `out_horizon_ms`, `out_interval_ms`,
 * `out_count`, and `out_resolution_ms` receives the corresponding value, or
 * `-1` when that field is absent (durations, resolution, and counts are always
 * non-negative when present, so `-1` is an unambiguous "unset" sentinel).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_present` must be valid for writing
 * one `bool`; every other output pointer must be valid for writing one `i64`.
 */
int32_t ts_store_get_forecast_parameters(const struct TsStore *handle,
                                         bool *out_present,
                                         int64_t *out_horizon_ms,
                                         int64_t *out_interval_ms,
                                         int64_t *out_count,
                                         int64_t *out_resolution_ms);

/**
 * Write the store's compression policy.
 *
 * `out_kind` receives `0` (no compression) or `1` (DEFLATE). For DEFLATE,
 * `out_level` (0-9) and `out_shuffle` receive the filter parameters; for no
 * compression they are set to `0` / `false`. This reflects the policy the
 * store was created with, restored from the file when the store was opened
 * (in-memory stores report `0`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `out_kind` and `out_level` must each be
 * valid for writing one `u8`; `out_shuffle` must be valid for writing one `bool`.
 */
int32_t ts_store_get_compression(const struct TsStore *handle,
                                 uint8_t *out_kind,
                                 uint8_t *out_level,
                                 bool *out_shuffle);

/**
 * Verify store integrity and return the number of detected errors.
 *
 * # Safety
 *
 * `handle` must be a live store handle and `out_error_count` must be valid for writing one `u64`.
 */
int32_t ts_store_verify(const struct TsStore *handle, uint64_t *out_error_count);

/**
 * Compact the store.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and must not be used concurrently for the duration
 * of the call.
 */
int32_t ts_store_compact(struct TsStore *handle);

/**
 * Flush pending store writes.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and must not be used concurrently for the duration
 * of the call.
 */
int32_t ts_store_flush(struct TsStore *handle);

/**
 * Look up a SingleTimeSeries metadata record by attributes. On success the
 * caller's out-params receive the initial timestamp, resolution, length, and
 * the 32-byte content hash (written into the `out_data_hash` buffer, which
 * must have room for 32 bytes). Returns `TS_ERR_NOT_FOUND` if absent.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` is a plain integer. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. Scalar output pointers must be valid for one
 * value and `out_data_hash` must be valid for 32 bytes.
 */
int32_t ts_store_get_metadata(const struct TsStore *handle,
                              int64_t owner_id,
                              const char *name,
                              int64_t resolution_ms,
                              const char *features_json,
                              int64_t *out_initial_ts_unix_ms,
                              int64_t *out_resolution_ms,
                              uint64_t *out_length,
                              uint8_t *out_data_hash,
                              int32_t *out_dtype,
                              char *out_logical_type,
                              uint64_t logical_type_cap,
                              uint64_t *out_logical_type_len);

/**
 * True iff a SingleTimeSeries with the given attributes exists.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` is a plain integer. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. `out_present` must be valid for writing one
 * `bool`.
 */
int32_t ts_store_has_by_attrs(const struct TsStore *handle,
                              int64_t owner_id,
                              const char *name,
                              int64_t resolution_ms,
                              const char *features_json,
                              bool *out_present);

/**
 * True iff `owner_id` has any time series, optionally filtered to a single
 * time series type (`use_type` selects whether `ts_type` is applied). Answers
 * the name-less `has_time_series(owner)` / `has_time_series(owner, T)` queries.
 *
 * # Safety
 *
 * `handle` must be a live store handle; `owner_id` is a plain integer;
 * `out_present` valid for writing one bool.
 */
int32_t ts_store_has_for_owner(const struct TsStore *handle,
                               int64_t owner_id,
                               int32_t ts_type,
                               bool use_type,
                               bool *out_present);

/**
 * Remove a SingleTimeSeries by attributes. Drops the underlying array iff no
 * other association still references its content hash.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required strings
 * must be null-terminated UTF-8, and `features_json` may be null.
 */
int32_t ts_store_remove_by_attrs(struct TsStore *handle,
                                 int64_t owner_id,
                                 const char *name,
                                 int64_t resolution_ms,
                                 const char *features_json);

/**
 * Fetch a stored array by its 32-byte content hash. On success the caller owns
 * `*out_data` and must free it with `ts_buffer_free_u8`.
 *
 * # Safety
 *
 * `handle` must be a live store handle, `data_hash` must reference 32 readable bytes, and every
 * output pointer must be valid for writing its indicated value. The returned buffer must be
 * released exactly once with `ts_buffer_free_u8` using the returned byte length.
 */
int32_t ts_store_get_array_by_hash(const struct TsStore *handle,
                                   const uint8_t *data_hash,
                                   int32_t *out_dtype,
                                   uint8_t **out_data,
                                   uint64_t *out_byte_len);

/**
 * Add a dense forecast. `data_ptr`/`data_byte_len` is the flattened storage
 * array (Deterministic: `[H, count, *E]`; Scenarios: `[scenario_count, H,
 * count, *E]`). `ts_type` must be 2=Deterministic or 5=Scenarios;
 * `DeterministicSingleTimeSeries` is not directly addable and is derived from a
 * stored `SingleTimeSeries` via `ts_store_transform_single_time_series`.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required strings
 * must be null-terminated UTF-8; optional strings may be null. `data_ptr` must reference `data_len`
 * elements and `out_key` must be valid for writing one pointer. The returned key must be released
 * with `ts_key_free`.
 */
int32_t ts_store_add_forecast(struct TsStore *handle,
                              int64_t owner_id,
                              const char *owner_type,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t initial_ts_unix_ms,
                              int64_t resolution_ms,
                              int64_t horizon_ms,
                              int64_t interval_ms,
                              uint64_t count,
                              int32_t dtype,
                              uint64_t ndims,
                              const uint64_t *dims_ptr,
                              const uint8_t *data_ptr,
                              uint64_t data_byte_len,
                              const char *logical_type,
                              const char *features_json,
                              const char *units,
                              struct TsKey **out_key);

/**
 * Add a `Probabilistic` forecast. `data` is the flattened 3-D storage array
 * `(percentile_count, horizon_count, count)` column-major; `percentiles` is the
 * percentile vector.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required strings
 * must be null-terminated UTF-8; optional strings may be null. `percentiles_ptr` and `data_ptr`
 * must reference their respective element counts, and `out_key` must be valid for writing one
 * pointer. The returned key must be released with `ts_key_free`.
 */
int32_t ts_store_add_probabilistic(struct TsStore *handle,
                                   int64_t owner_id,
                                   const char *owner_type,
                                   int32_t owner_category,
                                   const char *name,
                                   int64_t initial_ts_unix_ms,
                                   int64_t resolution_ms,
                                   int64_t horizon_ms,
                                   int64_t interval_ms,
                                   uint64_t count,
                                   const double *percentiles_ptr,
                                   uint64_t percentiles_len,
                                   int32_t dtype,
                                   uint64_t ndims,
                                   const uint64_t *dims_ptr,
                                   const uint8_t *data_ptr,
                                   uint64_t data_byte_len,
                                   const char *logical_type,
                                   const char *features_json,
                                   const char *units,
                                   struct TsKey **out_key);

/**
 * Create an empty add-batch. Building a batch performs no store I/O.
 *
 * # Safety
 *
 * The returned handle must be released exactly once with `ts_batch_free`
 * (regardless of whether it was submitted via `ts_store_add_batch`).
 */
struct TsBatch *ts_batch_new(void);

/**
 * Free a batch handle created by `ts_batch_new`.
 *
 * # Safety
 *
 * `batch` must be null or a handle returned by `ts_batch_new` that has not
 * already been freed.
 */
void ts_batch_free(struct TsBatch *batch);

/**
 * Append a SingleTimeSeries to a batch. Arguments match
 * `ts_store_add_single` (minus the store handle and `out_key`); the data is
 * copied into the batch, so the caller's buffers need only stay valid for
 * this call.
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `dims_ptr` must reference `ndims` elements when `ndims`
 * is nonzero, and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_single(struct TsBatch *batch,
                            int64_t owner_id,
                            const char *owner_type,
                            int32_t owner_category,
                            const char *name,
                            int64_t initial_ts_unix_ms,
                            int64_t resolution_ms,
                            int32_t dtype,
                            uint64_t ndims,
                            const uint64_t *dims_ptr,
                            const uint8_t *data_ptr,
                            uint64_t data_byte_len,
                            const char *logical_type,
                            const char *features_json,
                            const char *units);

/**
 * Append a NonSequentialTimeSeries to a batch. Arguments match
 * `ts_store_add_non_sequential` (minus the store handle and `out_key`).
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `timestamps_unix_ms` must reference `timestamps_len`
 * elements, `dims_ptr` must reference `ndims` elements when `ndims` is nonzero,
 * and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_non_sequential(struct TsBatch *batch,
                                    int64_t owner_id,
                                    const char *owner_type,
                                    int32_t owner_category,
                                    const char *name,
                                    const int64_t *timestamps_unix_ms,
                                    uint64_t timestamps_len,
                                    int32_t dtype,
                                    uint64_t ndims,
                                    const uint64_t *dims_ptr,
                                    const uint8_t *data_ptr,
                                    uint64_t data_byte_len,
                                    const char *logical_type,
                                    const char *features_json,
                                    const char *units);

/**
 * Append a dense forecast (`ts_type` 2=Deterministic or 5=Scenarios) to a
 * batch. Arguments match `ts_store_add_forecast` (minus the store handle and
 * `out_key`).
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `dims_ptr` must reference `ndims` elements when `ndims`
 * is nonzero, and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_forecast(struct TsBatch *batch,
                              int64_t owner_id,
                              const char *owner_type,
                              int32_t owner_category,
                              const char *name,
                              int32_t ts_type,
                              int64_t initial_ts_unix_ms,
                              int64_t resolution_ms,
                              int64_t horizon_ms,
                              int64_t interval_ms,
                              uint64_t count,
                              int32_t dtype,
                              uint64_t ndims,
                              const uint64_t *dims_ptr,
                              const uint8_t *data_ptr,
                              uint64_t data_byte_len,
                              const char *logical_type,
                              const char *features_json,
                              const char *units);

/**
 * Append a `Probabilistic` forecast to a batch. Arguments match
 * `ts_store_add_probabilistic` (minus the store handle and `out_key`).
 *
 * # Safety
 *
 * `batch` must be a live batch handle. `owner_id` is a plain integer. Required
 * string pointers must reference null-terminated UTF-8 strings; optional string
 * pointers may be null. `percentiles_ptr` must reference `percentiles_len`
 * elements, `dims_ptr` must reference `ndims` elements when `ndims` is nonzero,
 * and `data_ptr` must reference `data_byte_len` bytes.
 */
int32_t ts_batch_add_probabilistic(struct TsBatch *batch,
                                   int64_t owner_id,
                                   const char *owner_type,
                                   int32_t owner_category,
                                   const char *name,
                                   int64_t initial_ts_unix_ms,
                                   int64_t resolution_ms,
                                   int64_t horizon_ms,
                                   int64_t interval_ms,
                                   uint64_t count,
                                   const double *percentiles_ptr,
                                   uint64_t percentiles_len,
                                   int32_t dtype,
                                   uint64_t ndims,
                                   const uint64_t *dims_ptr,
                                   const uint8_t *data_ptr,
                                   uint64_t data_byte_len,
                                   const char *logical_type,
                                   const char *features_json,
                                   const char *units);

/**
 * Submit every request in `batch` through one all-or-nothing bulk add. On
 * success, writes an array of key handles (input order) to `out_keys` /
 * `out_len`. The batch is drained by this call in all cases — on error
 * nothing was committed and the batch is left empty; rebuild it before
 * retrying.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and `batch` a live batch
 * handle. `out_keys` and `out_len` must each be valid for writing one value.
 * On success the caller owns the returned array and every key handle in it:
 * release each key with `ts_key_free`, then the array buffer itself with
 * `ts_keys_buffer_free(*out_keys, *out_len)` (the same contract as
 * `ts_store_get_time_series_keys`).
 */
int32_t ts_store_add_batch(struct TsStore *handle,
                           struct TsBatch *batch,
                           struct TsKey ***out_keys,
                           uint64_t *out_len);

/**
 * Derive `DeterministicSingleTimeSeries` forecasts from the stored
 * `SingleTimeSeries` associations (see `Store::transform_single_time_series`).
 * Writes the number of series transformed to `*out_count`.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle and `out_count` must be valid
 * for writing one `u64`.
 */
int32_t ts_store_transform_single_time_series(struct TsStore *handle,
                                              int64_t horizon_ms,
                                              int64_t interval_ms,
                                              int32_t _owner_category,
                                              int64_t _resolution_ms,
                                              uint64_t *out_count);

/**
 * Read `Probabilistic` metadata. Like `ts_store_get_forecast_metadata` but also
 * returns the percentiles vector in `*out_percentiles` (caller frees with
 * `ts_buffer_free_f64`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` is a plain integer. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. Scalar output pointers must each be valid for
 * one value, `out_data_hash` must be valid for 32 bytes, and `out_percentiles` must be valid for
 * writing one pointer. The returned percentile buffer must be released exactly once with
 * `ts_buffer_free_f64` using the returned length.
 */
int32_t ts_store_get_probabilistic_metadata(const struct TsStore *handle,
                                            int64_t owner_id,
                                            const char *name,
                                            int64_t resolution_ms,
                                            const char *features_json,
                                            int64_t *out_initial_ts_unix_ms,
                                            int64_t *out_resolution_ms,
                                            int64_t *out_horizon_ms,
                                            int64_t *out_interval_ms,
                                            uint64_t *out_count,
                                            uint64_t *out_length,
                                            uint8_t *out_data_hash,
                                            double **out_percentiles,
                                            uint64_t *out_percentiles_len);

/**
 * Read forecast metadata by attributes. Out-params receive initial timestamp,
 * resolution, horizon, interval, count, the stored array length, and the
 * 32-byte content hash (into `out_data_hash`).
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` is a plain integer. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. Scalar output pointers must each be valid for
 * one value and `out_data_hash` must be valid for 32 bytes.
 */
int32_t ts_store_get_forecast_metadata(const struct TsStore *handle,
                                       int64_t owner_id,
                                       const char *name,
                                       int32_t ts_type,
                                       int64_t resolution_ms,
                                       const char *features_json,
                                       int64_t *out_initial_ts_unix_ms,
                                       int64_t *out_resolution_ms,
                                       int64_t *out_horizon_ms,
                                       int64_t *out_interval_ms,
                                       uint64_t *out_count,
                                       uint64_t *out_length,
                                       uint8_t *out_data_hash,
                                       char *logical_type_buf,
                                       uint64_t logical_type_cap,
                                       uint64_t *out_logical_type_len);

/**
 * Fetch a forecast by attributes and return the full data array plus metadata.
 *
 * Reads a `Deterministic`, `Probabilistic`, or `Scenarios` forecast (DST is
 * synthesized into `Deterministic`). On success, the caller owns two heap
 * buffers and must free them with the matching deallocators:
 *
 * - `*out_data` (byte buffer, `*out_data_byte_len` bytes) —
 *   free with `ts_buffer_free_u8(*out_data, *out_data_byte_len)`.
 * - `*out_dims` (array of `u64`, `*out_ndims` elements) —
 *   free with `ts_buffer_free_u64(*out_dims, *out_ndims)`.
 * - `*out_percentiles` (`f64` array, `*out_percentiles_len` elements) —
 *   non-NULL only for `Probabilistic`; free with
 *   `ts_buffer_free_f64(*out_percentiles, *out_percentiles_len)`.
 *
 * **Optional time-range / window selection:** when `time_range_present` is
 * `true`, only the windows whose start timestamp falls in
 * `[time_range_start_ms, time_range_end_ms)` are returned. Pass
 * `time_range_present = false` to retrieve all windows.
 *
 * # Safety
 *
 * - `handle` must be a live, non-null store handle created by this library.
 *   No concurrent mutation is permitted for the duration of the call.
 * - `owner_id` is a plain integer. `name` must point to a valid, null-terminated
 *   UTF-8 string for the duration of the call; `features_json` may be null.
 * - All `out_*` scalar pointers must be valid for writing one value each.
 * - `out_dims` must be valid for writing one pointer; the returned pointer
 *   must be freed exactly once with `ts_buffer_free_u64` using `*out_ndims`.
 * - `out_data` must be valid for writing one pointer; the returned pointer
 *   must be freed exactly once with `ts_buffer_free_u8` using
 *   `*out_data_byte_len`.
 * - `out_percentiles` must be valid for writing one pointer; when the result
 *   is not `Probabilistic` the pointer is set to null and `*out_percentiles_len`
 *   to 0, so no free is needed. When non-null it must be freed exactly once
 *   with `ts_buffer_free_f64` using `*out_percentiles_len`.
 * - All returned heap buffers are invalidated after their matching free call
 *   and must not be used afterwards.
 */
int32_t ts_store_get_forecast(const struct TsStore *handle,
                              int64_t owner_id,
                              const char *name,
                              int32_t ts_type,
                              int64_t resolution_ms,
                              const char *features_json,
                              bool time_range_present,
                              int64_t time_range_start_ms,
                              int64_t time_range_end_ms,
                              int64_t *out_initial_ts_unix_ms,
                              int64_t *out_resolution_ms,
                              int64_t *out_horizon_ms,
                              int64_t *out_interval_ms,
                              uint64_t *out_count,
                              uint64_t *out_scenario_count,
                              uint64_t *out_ndims,
                              uint64_t **out_dims,
                              int32_t *out_dtype,
                              uint8_t **out_data,
                              uint64_t *out_data_byte_len,
                              double **out_percentiles,
                              uint64_t *out_percentiles_len);

/**
 * Fetch a forecast (`Deterministic` / `Probabilistic` / `Scenarios`, or a
 * `DeterministicSingleTimeSeries` synthesized into a `Deterministic`) by key.
 *
 * This is the key-based counterpart to [`ts_store_get_forecast`]: the time
 * series type comes from `key` rather than an explicit `ts_type` argument. The
 * outputs and buffer-ownership rules are identical to [`ts_store_get_forecast`].
 *
 * # Safety
 *
 * - `handle` and `key` must be live handles created by this library; no
 *   concurrent mutation is permitted for the duration of the call.
 * - All `out_*` scalar pointers must be valid for writing one value each.
 * - `out_dims` must be valid for writing one pointer; the returned pointer must
 *   be freed exactly once with `ts_buffer_free_u64` using `*out_ndims`.
 * - `out_data` must be valid for writing one pointer; the returned pointer must
 *   be freed exactly once with `ts_buffer_free_u8` using `*out_data_byte_len`.
 * - `out_percentiles` must be valid for writing one pointer; when the result is
 *   not `Probabilistic` the pointer is set to null and `*out_percentiles_len`
 *   to 0, so no free is needed. When non-null it must be freed exactly once
 *   with `ts_buffer_free_f64` using `*out_percentiles_len`.
 */
int32_t ts_store_get_forecast_by_key(const struct TsStore *handle,
                                     const struct TsKey *key,
                                     bool time_range_present,
                                     int64_t time_range_start_ms,
                                     int64_t time_range_end_ms,
                                     int64_t *out_initial_ts_unix_ms,
                                     int64_t *out_resolution_ms,
                                     int64_t *out_horizon_ms,
                                     int64_t *out_interval_ms,
                                     uint64_t *out_count,
                                     uint64_t *out_scenario_count,
                                     uint64_t *out_ndims,
                                     uint64_t **out_dims,
                                     int32_t *out_dtype,
                                     uint8_t **out_data,
                                     uint64_t *out_data_byte_len,
                                     double **out_percentiles,
                                     uint64_t *out_percentiles_len);

/**
 * Construct a `TimeSeriesKey` handle from attributes `(owner_id, name,
 * ts_type, resolution, features)`.
 *
 * The returned key can be passed to the key-based read functions (e.g.
 * [`ts_store_get_single`], [`ts_store_get_non_sequential`],
 * [`ts_store_get_forecast_by_key`]); it lets an attribute-addressed caller
 * reuse the key-based read path without an `add`/lookup round trip.
 * `resolution_ms <= 0` means "unspecified".
 *
 * # Safety
 *
 * `owner_id` is a plain integer. `name` must point to a valid, null-terminated
 * UTF-8 string. `features_json`, when non-null, must be a null-terminated UTF-8
 * JSON object. `out_key` must be valid for writing one pointer. The returned key
 * must be released exactly once with `ts_key_free`.
 */
int32_t ts_make_key_from_attrs(int64_t owner_id,
                               const char *name,
                               int32_t ts_type,
                               int64_t resolution_ms,
                               const char *features_json,
                               struct TsKey **out_key);

/**
 * List every time series key associated with `owner_id`. On success
 * `*out_keys` points to an array of `*out_len` owned key handles (one per
 * association, including derived `DeterministicSingleTimeSeries` rows), each
 * usable with the key-based read functions.
 *
 * Ownership is two-tiered: free every individual `TsKey` with `ts_key_free`,
 * then free the array buffer itself with `ts_keys_buffer_free`. When the owner
 * has no series, `*out_keys` is set to null and `*out_len` to 0 (no free
 * needed).
 *
 * # Safety
 *
 * `handle` must be a live store handle and `owner_id` is a plain integer.
 * `out_keys` must be valid for writing one pointer and `out_len` for writing one
 * `u64`.
 */
int32_t ts_store_get_time_series_keys(const struct TsStore *handle,
                                      int64_t owner_id,
                                      struct TsKey ***out_keys,
                                      uint64_t *out_len);

/**
 * List time series metadata as a JSON array string (see `metadata_rows_to_json`
 * for the per-row shape). When `has_owner` is true only `owner_id`'s rows
 * are returned; otherwise the whole store is listed.
 *
 * Follows the probe-then-fetch convention: call with `buf` null and `cap` 0 to
 * learn the byte length via `out_len`, then call again with a buffer of at
 * least `len + 1` bytes. The string is NUL-terminated and truncated to `cap`;
 * `out_len` is always the untruncated byte length.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `has_owner` and `owner_id` are plain
 * scalars. `out_len` must be writable; `buf` must be null or valid for `cap`
 * bytes.
 */
int32_t ts_store_list_metadata(const struct TsStore *handle,
                               bool has_owner,
                               int64_t owner_id,
                               char *buf,
                               uint64_t cap,
                               uint64_t *out_len);

/**
 * Free the key-handle array returned by `ts_store_get_time_series_keys`.
 *
 * This releases only the array buffer, not the keys it held: transfer each
 * `TsKey` out first (the Julia binding wraps each in a finalized object) and
 * release them individually with `ts_key_free`.
 *
 * # Safety
 *
 * `ptr` must be null or an array returned by `ts_store_get_time_series_keys`
 * with exactly `len` elements, not previously freed. It must not be used after
 * this call.
 */
void ts_keys_buffer_free(struct TsKey **ptr, uint64_t len);

/**
 * Read the attributes of a key handle: its time series type code (see
 * `ts_type_from_int`), resolution in milliseconds (`0` when unset), the owner
 * id (an integer), the name string, and the features as a JSON object string
 * (`"{}"` when empty — the same shape the attribute-addressed entry points
 * accept).
 *
 * `out_owner_id` receives the owner id directly. The `name` and `features`
 * strings follow the probe-then-fetch convention: call with `name_buf` /
 * `features_buf` null (and capacities `0`) to learn the required lengths via the
 * matching `out_*_len`, then call again with buffers of at least `len + 1`
 * bytes. Each returned string is NUL-terminated and truncated to its capacity;
 * the reported length is always the untruncated byte length.
 *
 * # Safety
 *
 * `key` must be a live key handle created by this library. `out_type`,
 * `out_resolution_ms`, `out_owner_id`, `out_name_len`, and `out_features_len`
 * must each be valid for writing one value. `name_buf` / `features_buf` may be
 * null; when non-null they must be valid for writing `name_cap` / `features_cap`
 * bytes respectively.
 */
int32_t ts_key_attributes(const struct TsKey *key,
                          int32_t *out_type,
                          int64_t *out_resolution_ms,
                          int64_t *out_owner_id,
                          char *name_buf,
                          uint64_t name_cap,
                          uint64_t *out_name_len,
                          char *features_buf,
                          uint64_t features_cap,
                          uint64_t *out_features_len);

/**
 * Read an association's `name` by key, resolved through the stored metadata
 * (`Store::get_metadata`). This surfaces the per-association `name` that is not
 * carried on the key itself — the read path uses it to populate the returned
 * time series object.
 *
 * `name` uses the probe-then-fetch convention (see [`ts_key_attributes`]).
 *
 * # Safety
 *
 * `handle` and `key` must be live handles created by this library.
 * `out_name_len` must be valid for writing one `u64`. `name_buf` may be null;
 * when non-null it must be valid for writing `name_cap` bytes.
 */
int32_t ts_store_get_association(const struct TsStore *handle,
                                 const struct TsKey *key,
                                 char *name_buf,
                                 uint64_t name_cap,
                                 uint64_t *out_name_len);

/**
 * Release a `u64` dims buffer returned by `ts_store_get_forecast`.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` elements. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_u64(uint64_t *ptr, uint64_t len);

/**
 * True iff a time series of `ts_type` with the given attributes exists.
 *
 * # Safety
 *
 * `handle` must be a live store handle. `owner_id` is a plain integer. Required strings must be
 * null-terminated UTF-8; `features_json` may be null. `out_present` must be valid for writing one
 * `bool`.
 */
int32_t ts_store_has_typed(const struct TsStore *handle,
                           int64_t owner_id,
                           const char *name,
                           int32_t ts_type,
                           int64_t resolution_ms,
                           const char *features_json,
                           bool *out_present);

/**
 * Remove a time series of `ts_type` by attributes.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `owner_id` is a plain integer. Required strings
 * must be null-terminated UTF-8, and `features_json` may be null.
 */
int32_t ts_store_remove_typed(struct TsStore *handle,
                              int64_t owner_id,
                              const char *name,
                              int32_t ts_type,
                              int64_t resolution_ms,
                              const char *features_json);

/**
 * Remove all time series, or all for a single owner when `has_owner` is true.
 * Returns `TS_OK` on success.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `has_owner` and `owner_id` are
 * plain scalars.
 */
int32_t ts_store_clear(struct TsStore *handle, bool has_owner, int64_t owner_id);

/**
 * Reassign every time series owned by `old_owner_id` to `new_owner_id`.
 * When `out_updated` is non-null it receives the number of associations
 * changed. Returns `TS_OK` on success.
 *
 * # Safety
 *
 * `handle` must be a live mutable store handle. `old_owner_id` and
 * `new_owner_id` are plain integers. When non-null, `out_updated` must point to
 * writable `u64` storage.
 */
int32_t ts_store_replace_owner(struct TsStore *handle,
                               int64_t old_owner_id,
                               int64_t new_owner_id,
                               uint64_t *out_updated);

/**
 * Release a key handle returned by this library.
 *
 * # Safety
 *
 * `key` must be null or a live key handle returned by this library that has not already been
 * freed. The key must not be used after this call.
 */
void ts_key_free(struct TsKey *key);

/**
 * Release an `f64` buffer returned by this library.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` elements. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_f64(double *ptr, uint64_t len);

/**
 * Free a `u8` buffer returned by `ts_store_get_array_by_hash`.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` bytes. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_u8(uint8_t *ptr, uint64_t len);

/**
 * Free an `i64` buffer returned by `ts_store_get_non_sequential`.
 *
 * # Safety
 *
 * `ptr` must be null or a buffer returned by this library with exactly `len` elements. It must not
 * have been freed previously and must not be used after this call.
 */
void ts_buffer_free_i64(int64_t *ptr, uint64_t len);

/**
 * Copy the thread-local error message into `buf` (UTF-8, null-terminated).
 * Returns the number of bytes that would have been written (excluding the NUL)
 * in `*needed`. If `buf_len` is too small, `buf` is filled up to its length
 * and truncated; the function still returns `TS_OK` and the caller can decide
 * whether to retry with a larger buffer.
 *
 * # Safety
 *
 * `needed` may be null; otherwise it must be valid for writing one `u64`. `buf` may be null when
 * `buf_len` is zero; otherwise it must reference at least `buf_len` writable bytes.
 */
int32_t ts_last_error_message(char *buf, uint64_t buf_len, uint64_t *needed);

#endif  /* TIME_SERIES_STORE_H */
