name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/scripts/check-doc-links.py'
      - '.github/scripts/update-versions-json.py'
      - '.github/workflows/docs.yml'
      - '.github/workflows/docs-deploy.yml'

jobs:
  deploy:
    # contents:write is required to push to the gh-pages branch directly
    permissions:
      contents: write
    uses: ./.github/workflows/docs-deploy.yml
    with:
      version: latest
